/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonGroupState } from "./components/button/sy-button";
export { ButtonGroupState } from "./components/button/sy-button";
export namespace Components {
    interface SyBannerMesssage {
        /**
          * @default false
         */
        "closable": boolean;
        /**
          * @default ''
         */
        "header": string;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default ''
         */
        "neutralIcon": string;
        /**
          * @default false
         */
        "showIcon": boolean;
        /**
          * @default 'info'
         */
        "variant": 'info' | 'success' | 'warning' | 'error' | 'neutral';
    }
    interface SyBreadcrumb {
        /**
          * @default 'slash'
         */
        "separator": 'slash' | 'arrow';
    }
    interface SyBreadcrumbItem {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "forceUpdate": () => Promise<void>;
        /**
          * @default false
         */
        "isLast": boolean;
        /**
          * @default 'slash'
         */
        "parentSeparator": 'slash' | 'arrow';
        "separator"?: 'slash' | 'arrow';
    }
    interface SyButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "formnovalidate": boolean;
        /**
          * @default false
         */
        "justified": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        "setBlur": () => Promise<void>;
        "setButtonGroupState": (state: ButtonGroupState) => Promise<void>;
        "setClick": () => Promise<void>;
        "setFocus": () => Promise<void>;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'primary' | 'secondary' | 'borderless';
    }
    interface SyButtonGroup {
        /**
          * @default false
         */
        "vertical": boolean;
    }
    interface SyCheckbox {
        "checkValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "checked": boolean;
        "clearCustomError": () => Promise<void>;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "indeterminate": boolean;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default false
         */
        "readonly": boolean;
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        "setBlur": () => Promise<void>;
        "setCustomError": () => Promise<void>;
        "setFocus": () => Promise<void>;
        /**
          * @default ''
         */
        "titleText": string;
    }
    interface SyDivider {
        /**
          * @default 'horizontal'
         */
        "type": 'horizontal' | 'vertical';
    }
    interface SyDrawer {
        /**
          * @default false
         */
        "closable": boolean;
        /**
          * @default 100
         */
        "customSize": number;
        /**
          * @default false
         */
        "maskless": boolean;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'right'
         */
        "position": 'top' | 'left' | 'right' | 'bottom';
        /**
          * @default false
         */
        "preventClose": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large' | 'custom';
    }
    interface SyEmpty {
        /**
          * Empty 컴포넌트에 표시될 설명 텍스트입니다. Lit의
          * @property에 해당합니다.
         */
        "description": string;
    }
    interface SyIcon {
        "path"?: string;
        /**
          * @default false
         */
        "selectable": boolean;
        /**
          * @default 'medium'
         */
        "size": 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge' | 'xxxlarge';
    }
    interface SySpinner {
        /**
          * @default 0
         */
        "delay": number;
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default false
         */
        "hidden": boolean;
        /**
          * @default false
         */
        "inline": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large' | 'xlarge';
    }
    interface SyTag {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "removable": boolean;
        /**
          * @default false
         */
        "rounded": boolean;
        /**
          * @default false
         */
        "selectable": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'gray'
         */
        "variant": 'gray' | 'purple' | 'blue' | 'green' | 'cyan' | 'yellow' | 'orange' | 'red';
    }
}
export interface SyBreadcrumbItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyBreadcrumbItemElement;
}
export interface SyCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyCheckboxElement;
}
export interface SyDrawerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyDrawerElement;
}
export interface SyIconCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyIconElement;
}
export interface SyTagCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyTagElement;
}
declare global {
    interface HTMLSyBannerMesssageElement extends Components.SyBannerMesssage, HTMLStencilElement {
    }
    var HTMLSyBannerMesssageElement: {
        prototype: HTMLSyBannerMesssageElement;
        new (): HTMLSyBannerMesssageElement;
    };
    interface HTMLSyBreadcrumbElement extends Components.SyBreadcrumb, HTMLStencilElement {
    }
    var HTMLSyBreadcrumbElement: {
        prototype: HTMLSyBreadcrumbElement;
        new (): HTMLSyBreadcrumbElement;
    };
    interface HTMLSyBreadcrumbItemElementEventMap {
        "selected": HTMLElement;
    }
    interface HTMLSyBreadcrumbItemElement extends Components.SyBreadcrumbItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyBreadcrumbItemElementEventMap>(type: K, listener: (this: HTMLSyBreadcrumbItemElement, ev: SyBreadcrumbItemCustomEvent<HTMLSyBreadcrumbItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyBreadcrumbItemElementEventMap>(type: K, listener: (this: HTMLSyBreadcrumbItemElement, ev: SyBreadcrumbItemCustomEvent<HTMLSyBreadcrumbItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyBreadcrumbItemElement: {
        prototype: HTMLSyBreadcrumbItemElement;
        new (): HTMLSyBreadcrumbItemElement;
    };
    interface HTMLSyButtonElement extends Components.SyButton, HTMLStencilElement {
    }
    var HTMLSyButtonElement: {
        prototype: HTMLSyButtonElement;
        new (): HTMLSyButtonElement;
    };
    interface HTMLSyButtonGroupElement extends Components.SyButtonGroup, HTMLStencilElement {
    }
    var HTMLSyButtonGroupElement: {
        prototype: HTMLSyButtonGroupElement;
        new (): HTMLSyButtonGroupElement;
    };
    interface HTMLSyCheckboxElementEventMap {
        "changed": { value: boolean; isValid: boolean; checked: boolean; indeterminate: boolean; };
        "focused": boolean;
        "blured": boolean;
    }
    interface HTMLSyCheckboxElement extends Components.SyCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyCheckboxElementEventMap>(type: K, listener: (this: HTMLSyCheckboxElement, ev: SyCheckboxCustomEvent<HTMLSyCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyCheckboxElementEventMap>(type: K, listener: (this: HTMLSyCheckboxElement, ev: SyCheckboxCustomEvent<HTMLSyCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyCheckboxElement: {
        prototype: HTMLSyCheckboxElement;
        new (): HTMLSyCheckboxElement;
    };
    interface HTMLSyDividerElement extends Components.SyDivider, HTMLStencilElement {
    }
    var HTMLSyDividerElement: {
        prototype: HTMLSyDividerElement;
        new (): HTMLSyDividerElement;
    };
    interface HTMLSyDrawerElementEventMap {
        "opened": void;
        "closed": void;
    }
    interface HTMLSyDrawerElement extends Components.SyDrawer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyDrawerElementEventMap>(type: K, listener: (this: HTMLSyDrawerElement, ev: SyDrawerCustomEvent<HTMLSyDrawerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyDrawerElementEventMap>(type: K, listener: (this: HTMLSyDrawerElement, ev: SyDrawerCustomEvent<HTMLSyDrawerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyDrawerElement: {
        prototype: HTMLSyDrawerElement;
        new (): HTMLSyDrawerElement;
    };
    interface HTMLSyEmptyElement extends Components.SyEmpty, HTMLStencilElement {
    }
    var HTMLSyEmptyElement: {
        prototype: HTMLSyEmptyElement;
        new (): HTMLSyEmptyElement;
    };
    interface HTMLSyIconElementEventMap {
        "selected": { value: string };
    }
    interface HTMLSyIconElement extends Components.SyIcon, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyIconElementEventMap>(type: K, listener: (this: HTMLSyIconElement, ev: SyIconCustomEvent<HTMLSyIconElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyIconElementEventMap>(type: K, listener: (this: HTMLSyIconElement, ev: SyIconCustomEvent<HTMLSyIconElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyIconElement: {
        prototype: HTMLSyIconElement;
        new (): HTMLSyIconElement;
    };
    interface HTMLSySpinnerElement extends Components.SySpinner, HTMLStencilElement {
    }
    var HTMLSySpinnerElement: {
        prototype: HTMLSySpinnerElement;
        new (): HTMLSySpinnerElement;
    };
    interface HTMLSyTagElementEventMap {
        "selected": { tag: HTMLElement };
        "removed": { tag: HTMLElement };
    }
    interface HTMLSyTagElement extends Components.SyTag, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyTagElementEventMap>(type: K, listener: (this: HTMLSyTagElement, ev: SyTagCustomEvent<HTMLSyTagElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyTagElementEventMap>(type: K, listener: (this: HTMLSyTagElement, ev: SyTagCustomEvent<HTMLSyTagElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyTagElement: {
        prototype: HTMLSyTagElement;
        new (): HTMLSyTagElement;
    };
    interface HTMLElementTagNameMap {
        "sy-banner-messsage": HTMLSyBannerMesssageElement;
        "sy-breadcrumb": HTMLSyBreadcrumbElement;
        "sy-breadcrumb-item": HTMLSyBreadcrumbItemElement;
        "sy-button": HTMLSyButtonElement;
        "sy-button-group": HTMLSyButtonGroupElement;
        "sy-checkbox": HTMLSyCheckboxElement;
        "sy-divider": HTMLSyDividerElement;
        "sy-drawer": HTMLSyDrawerElement;
        "sy-empty": HTMLSyEmptyElement;
        "sy-icon": HTMLSyIconElement;
        "sy-spinner": HTMLSySpinnerElement;
        "sy-tag": HTMLSyTagElement;
    }
}
declare namespace LocalJSX {
    interface SyBannerMesssage {
        /**
          * @default false
         */
        "closable"?: boolean;
        /**
          * @default ''
         */
        "header"?: string;
        /**
          * @default ''
         */
        "message"?: string;
        /**
          * @default ''
         */
        "neutralIcon"?: string;
        /**
          * @default false
         */
        "showIcon"?: boolean;
        /**
          * @default 'info'
         */
        "variant"?: 'info' | 'success' | 'warning' | 'error' | 'neutral';
    }
    interface SyBreadcrumb {
        /**
          * @default 'slash'
         */
        "separator"?: 'slash' | 'arrow';
    }
    interface SyBreadcrumbItem {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "isLast"?: boolean;
        "onSelected"?: (event: SyBreadcrumbItemCustomEvent<HTMLElement>) => void;
        /**
          * @default 'slash'
         */
        "parentSeparator"?: 'slash' | 'arrow';
        "separator"?: 'slash' | 'arrow';
    }
    interface SyButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "formnovalidate"?: boolean;
        /**
          * @default false
         */
        "justified"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'primary' | 'secondary' | 'borderless';
    }
    interface SyButtonGroup {
        /**
          * @default false
         */
        "vertical"?: boolean;
    }
    interface SyCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * @default ''
         */
        "name"?: string;
        "onBlured"?: (event: SyCheckboxCustomEvent<boolean>) => void;
        "onChanged"?: (event: SyCheckboxCustomEvent<{ value: boolean; isValid: boolean; checked: boolean; indeterminate: boolean; }>) => void;
        "onFocused"?: (event: SyCheckboxCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "titleText"?: string;
    }
    interface SyDivider {
        /**
          * @default 'horizontal'
         */
        "type"?: 'horizontal' | 'vertical';
    }
    interface SyDrawer {
        /**
          * @default false
         */
        "closable"?: boolean;
        /**
          * @default 100
         */
        "customSize"?: number;
        /**
          * @default false
         */
        "maskless"?: boolean;
        "onClosed"?: (event: SyDrawerCustomEvent<void>) => void;
        "onOpened"?: (event: SyDrawerCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'right'
         */
        "position"?: 'top' | 'left' | 'right' | 'bottom';
        /**
          * @default false
         */
        "preventClose"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | 'custom';
    }
    interface SyEmpty {
        /**
          * Empty 컴포넌트에 표시될 설명 텍스트입니다. Lit의
          * @property에 해당합니다.
         */
        "description"?: string;
    }
    interface SyIcon {
        "onSelected"?: (event: SyIconCustomEvent<{ value: string }>) => void;
        "path"?: string;
        /**
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge' | 'xxxlarge';
    }
    interface SySpinner {
        /**
          * @default 0
         */
        "delay"?: number;
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default false
         */
        "hidden"?: boolean;
        /**
          * @default false
         */
        "inline"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | 'xlarge';
    }
    interface SyTag {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onRemoved"?: (event: SyTagCustomEvent<{ tag: HTMLElement }>) => void;
        "onSelected"?: (event: SyTagCustomEvent<{ tag: HTMLElement }>) => void;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "removable"?: boolean;
        /**
          * @default false
         */
        "rounded"?: boolean;
        /**
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'gray'
         */
        "variant"?: 'gray' | 'purple' | 'blue' | 'green' | 'cyan' | 'yellow' | 'orange' | 'red';
    }
    interface IntrinsicElements {
        "sy-banner-messsage": SyBannerMesssage;
        "sy-breadcrumb": SyBreadcrumb;
        "sy-breadcrumb-item": SyBreadcrumbItem;
        "sy-button": SyButton;
        "sy-button-group": SyButtonGroup;
        "sy-checkbox": SyCheckbox;
        "sy-divider": SyDivider;
        "sy-drawer": SyDrawer;
        "sy-empty": SyEmpty;
        "sy-icon": SyIcon;
        "sy-spinner": SySpinner;
        "sy-tag": SyTag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-banner-messsage": LocalJSX.SyBannerMesssage & JSXBase.HTMLAttributes<HTMLSyBannerMesssageElement>;
            "sy-breadcrumb": LocalJSX.SyBreadcrumb & JSXBase.HTMLAttributes<HTMLSyBreadcrumbElement>;
            "sy-breadcrumb-item": LocalJSX.SyBreadcrumbItem & JSXBase.HTMLAttributes<HTMLSyBreadcrumbItemElement>;
            "sy-button": LocalJSX.SyButton & JSXBase.HTMLAttributes<HTMLSyButtonElement>;
            "sy-button-group": LocalJSX.SyButtonGroup & JSXBase.HTMLAttributes<HTMLSyButtonGroupElement>;
            "sy-checkbox": LocalJSX.SyCheckbox & JSXBase.HTMLAttributes<HTMLSyCheckboxElement>;
            "sy-divider": LocalJSX.SyDivider & JSXBase.HTMLAttributes<HTMLSyDividerElement>;
            "sy-drawer": LocalJSX.SyDrawer & JSXBase.HTMLAttributes<HTMLSyDrawerElement>;
            "sy-empty": LocalJSX.SyEmpty & JSXBase.HTMLAttributes<HTMLSyEmptyElement>;
            "sy-icon": LocalJSX.SyIcon & JSXBase.HTMLAttributes<HTMLSyIconElement>;
            "sy-spinner": LocalJSX.SySpinner & JSXBase.HTMLAttributes<HTMLSySpinnerElement>;
            "sy-tag": LocalJSX.SyTag & JSXBase.HTMLAttributes<HTMLSyTagElement>;
        }
    }
}
