/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HTMLSyBreadcrumbItemElement } from "./components/breadcrumb/sy-breadcrumb-item";
import { ButtonGroupState } from "./components/button-group";
export { HTMLSyBreadcrumbItemElement } from "./components/breadcrumb/sy-breadcrumb-item";
export { ButtonGroupState } from "./components/button-group";
export namespace Components {
    interface SyAvatar {
        /**
          * @default false
         */
        "clickable": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "icon": string;
        /**
          * @default ''
         */
        "image": string;
        /**
          * @default ''
         */
        "letter": string;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default ''
         */
        "text": string;
        /**
          * @default ''
         */
        "tooltipContent": string;
        /**
          * @default "lightgray"
         */
        "variant": "lightgray"| "red" | "orange" | "yellow" | "lime" | "green" | "teal" | "blue" | "purple" | "magenta" | "darkgray";
    }
    interface SyBadge {
        /**
          * @default false
         */
        "dot": boolean;
        /**
          * @default false
         */
        "hidden": boolean;
        /**
          * @default Infinity
         */
        "overflowCount": number;
        /**
          * @default 'topRight'
         */
        "position": 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight';
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium';
        /**
          * @default false
         */
        "standalone": boolean;
        /**
          * @default 0
         */
        "value": number;
        /**
          * @default 'red'
         */
        "variant": 'red' | 'yellow' | 'green' | 'blue' | 'gray';
    }
    interface SyBannerMesssage {
        /**
          * @default false
         */
        "closable": boolean;
        /**
          * @default ''
         */
        "header": string;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default ''
         */
        "neutralIcon": string;
        /**
          * @default false
         */
        "showIcon": boolean;
        /**
          * @default 'info'
         */
        "variant": 'info' | 'success' | 'warning' | 'error' | 'neutral';
    }
    interface SyBreadcrumb {
        /**
          * @default 'slash'
         */
        "separator": 'slash' | 'arrow';
    }
    interface SyBreadcrumbItem {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "forceUpdate": () => Promise<void>;
        /**
          * @default false
         */
        "isLast": boolean;
        /**
          * @default 'slash'
         */
        "parentSeparator": 'slash' | 'arrow';
        "separator"?: 'slash' | 'arrow';
    }
    interface SyButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "formnovalidate": boolean;
        /**
          * @default false
         */
        "justified": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        "setBlur": () => Promise<void>;
        "setButtonGroupState": (state: ButtonGroupState) => Promise<void>;
        "setClick": () => Promise<void>;
        "setFocus": () => Promise<void>;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'primary' | 'secondary' | 'borderless';
    }
    interface SyButtonGroup {
        /**
          * @default false
         */
        "vertical": boolean;
    }
    interface SyCheckbox {
        "checkValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "checked": boolean;
        "clearCustomError": () => Promise<void>;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "indeterminate": boolean;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default false
         */
        "readonly": boolean;
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        "setBlur": () => Promise<void>;
        "setCustomError": () => Promise<void>;
        "setFocus": () => Promise<void>;
        /**
          * @default ''
         */
        "titleText": string;
    }
    interface SyDivider {
        /**
          * @default 'horizontal'
         */
        "type": 'horizontal' | 'vertical';
    }
    interface SyDrawer {
        /**
          * @default false
         */
        "closable": boolean;
        /**
          * @default 100
         */
        "customSize": number;
        /**
          * @default false
         */
        "maskless": boolean;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'right'
         */
        "position": 'top' | 'left' | 'right' | 'bottom';
        /**
          * @default false
         */
        "preventClose": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large' | 'custom';
    }
    interface SyEmpty {
        /**
          * Empty 컴포넌트에 표시될 설명 텍스트입니다. Lit의
          * @property에 해당합니다.
         */
        "description": string;
    }
    interface SyIcon {
        "path"?: string;
        /**
          * @default false
         */
        "selectable": boolean;
        /**
          * @default 'medium'
         */
        "size": 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge' | 'xxxlarge';
    }
    interface SyInput {
        /**
          * @default false
         */
        "autofocus": boolean;
        /**
          * @default false
         */
        "borderless": boolean;
        "checkValidity": () => Promise<boolean>;
        "clearCustomError": () => Promise<void>;
        /**
          * @default false
         */
        "clearable": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "getStatus": () => Promise<"" | "custom" | "valueMissing" | "tooShort" | "tooLong">;
        /**
          * @default ""
         */
        "label": string;
        "max"?: number;
        "min"?: number;
        /**
          * @default ""
         */
        "name": string;
        /**
          * @default false
         */
        "noNativeValidity": boolean;
        /**
          * @default ""
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        "setBlur": () => Promise<void>;
        "setCustomError": () => Promise<void>;
        "setFocus": () => Promise<void>;
        /**
          * @default "medium"
         */
        "size": "small" | "medium" | "large";
        /**
          * @default 'default'
         */
        "status": 'default' | 'warning' | 'error' | 'success';
        /**
          * @default ""
         */
        "value": string;
        /**
          * @default "text"
         */
        "variant": "password" | "search" | "text";
    }
    /**
     * 팝오버 컴포넌트 - 다른 요소에 부가 정보를 표시하는 오버레이 요소
     * 마우스 호버, 클릭, 포커스 등의 트리거로 활성화됩니다.
     */
    interface SyPopover {
        /**
          * @default false
         */
        "arrow": boolean;
        /**
          * @default 100
         */
        "closedelay": number;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 0
         */
        "opendelay": number;
        /**
          * @default 'bottom'
         */
        "position": 'top' | 'bottom' | 'left' | 'right' | 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight' | 'leftTop' | 'leftBottom' | 'rightTop' | 'rightBottom';
        /**
          * 팝업을 닫기 위한 공개 메서드
         */
        "setClose": () => Promise<void>;
        /**
          * 팝업을 열기 위한 공개 메서드
         */
        "setOpen": () => Promise<void>;
        /**
          * @default false
         */
        "sticky": boolean;
        /**
          * @default 'hover'
         */
        "trigger": 'hover' | 'click' | 'focus' | 'null';
    }
    interface SySpinner {
        /**
          * @default 0
         */
        "delay": number;
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default false
         */
        "hidden": boolean;
        /**
          * @default false
         */
        "inline": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large' | 'xlarge';
    }
    interface SySplitPanel {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "hideDivider": boolean;
        /**
          * @default 0
         */
        "minRatio": number;
        /**
          * @default 50
         */
        "ratio": number;
        /**
          * @default 'horizontal'
         */
        "type": 'horizontal' | 'vertical';
    }
    interface SySwitch {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "label": string;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium';
    }
    interface SyTag {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "removable": boolean;
        /**
          * @default false
         */
        "rounded": boolean;
        /**
          * @default false
         */
        "selectable": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'gray'
         */
        "variant": 'gray' | 'purple' | 'blue' | 'green' | 'cyan' | 'yellow' | 'orange' | 'red';
    }
    interface SyTextarea {
        /**
          * @default false
         */
        "autofocus": boolean;
        /**
          * @default false
         */
        "borderless": boolean;
        "checkValidity": () => Promise<boolean>;
        "clearCustomError": () => Promise<void>;
        /**
          * @default false
         */
        "clearable": boolean;
        /**
          * @default false
         */
        "counter": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "getStatus": () => Promise<"" | "custom" | "valueMissing" | "tooShort" | "tooLong">;
        /**
          * @default ""
         */
        "label": string;
        /**
          * @default Number.MAX_SAFE_INTEGER
         */
        "max": number;
        /**
          * @default 0
         */
        "min": number;
        /**
          * @default ""
         */
        "name": string;
        /**
          * @default false
         */
        "noNativeValidity": boolean;
        /**
          * @default ""
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default "none"
         */
        "resize": "none" | "horizontal" | "vertical" | "both";
        /**
          * @default 4
         */
        "rows": number;
        "setBlur": () => Promise<void>;
        "setCustomError": () => Promise<void>;
        "setFocus": () => Promise<void>;
        /**
          * @default "medium"
         */
        "size": "small" | "medium" | "large";
        /**
          * @default 'default'
         */
        "status": 'default' | 'warning' | 'error' | 'success';
        /**
          * @default ""
         */
        "value": string;
    }
    interface SyTooltip {
        /**
          * @default 0
         */
        "closedelay": number;
        /**
          * @default ''
         */
        "content": string;
        /**
          * @default false
         */
        "hideArrow": boolean;
        /**
          * @default null
         */
        "maxWidth": number | null;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 0
         */
        "opendelay": number;
        /**
          * @default 'top'
         */
        "position": 'top' | 'topLeft' | 'topRight' | 'right' | 'rightTop' | 'rightBottom' | 'bottom' | 'bottomLeft' | 'bottomRight' | 'left' | 'leftTop' | 'leftBottom';
        /**
          * @default 'hover'
         */
        "trigger": 'hover' | 'click' | 'focus' | 'none';
    }
}
export interface SyAvatarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyAvatarElement;
}
export interface SyBreadcrumbItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyBreadcrumbItemElement;
}
export interface SyCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyCheckboxElement;
}
export interface SyDrawerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyDrawerElement;
}
export interface SyIconCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyIconElement;
}
export interface SyInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyInputElement;
}
export interface SySplitPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSySplitPanelElement;
}
export interface SySwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSySwitchElement;
}
export interface SyTagCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyTagElement;
}
export interface SyTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyTextareaElement;
}
declare global {
    interface HTMLSyAvatarElementEventMap {
        "selected": {
    letter: string;
    text: string;
    icon: string;
    image: string;
  };
        "disableStatus": { disabled: boolean };
    }
    interface HTMLSyAvatarElement extends Components.SyAvatar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyAvatarElementEventMap>(type: K, listener: (this: HTMLSyAvatarElement, ev: SyAvatarCustomEvent<HTMLSyAvatarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyAvatarElementEventMap>(type: K, listener: (this: HTMLSyAvatarElement, ev: SyAvatarCustomEvent<HTMLSyAvatarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyAvatarElement: {
        prototype: HTMLSyAvatarElement;
        new (): HTMLSyAvatarElement;
    };
    interface HTMLSyBadgeElement extends Components.SyBadge, HTMLStencilElement {
    }
    var HTMLSyBadgeElement: {
        prototype: HTMLSyBadgeElement;
        new (): HTMLSyBadgeElement;
    };
    interface HTMLSyBannerMesssageElement extends Components.SyBannerMesssage, HTMLStencilElement {
    }
    var HTMLSyBannerMesssageElement: {
        prototype: HTMLSyBannerMesssageElement;
        new (): HTMLSyBannerMesssageElement;
    };
    interface HTMLSyBreadcrumbElement extends Components.SyBreadcrumb, HTMLStencilElement {
    }
    var HTMLSyBreadcrumbElement: {
        prototype: HTMLSyBreadcrumbElement;
        new (): HTMLSyBreadcrumbElement;
    };
    interface HTMLSyBreadcrumbItemElementEventMap {
        "selected": HTMLSyBreadcrumbItemElement;
    }
    interface HTMLSyBreadcrumbItemElement extends Components.SyBreadcrumbItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyBreadcrumbItemElementEventMap>(type: K, listener: (this: HTMLSyBreadcrumbItemElement, ev: SyBreadcrumbItemCustomEvent<HTMLSyBreadcrumbItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyBreadcrumbItemElementEventMap>(type: K, listener: (this: HTMLSyBreadcrumbItemElement, ev: SyBreadcrumbItemCustomEvent<HTMLSyBreadcrumbItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyBreadcrumbItemElement: {
        prototype: HTMLSyBreadcrumbItemElement;
        new (): HTMLSyBreadcrumbItemElement;
    };
    interface HTMLSyButtonElement extends Components.SyButton, HTMLStencilElement {
    }
    var HTMLSyButtonElement: {
        prototype: HTMLSyButtonElement;
        new (): HTMLSyButtonElement;
    };
    interface HTMLSyButtonGroupElement extends Components.SyButtonGroup, HTMLStencilElement {
    }
    var HTMLSyButtonGroupElement: {
        prototype: HTMLSyButtonGroupElement;
        new (): HTMLSyButtonGroupElement;
    };
    interface HTMLSyCheckboxElementEventMap {
        "changed": { value: boolean; isValid: boolean; checked: boolean; indeterminate: boolean; };
        "focused": boolean;
        "blured": boolean;
    }
    interface HTMLSyCheckboxElement extends Components.SyCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyCheckboxElementEventMap>(type: K, listener: (this: HTMLSyCheckboxElement, ev: SyCheckboxCustomEvent<HTMLSyCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyCheckboxElementEventMap>(type: K, listener: (this: HTMLSyCheckboxElement, ev: SyCheckboxCustomEvent<HTMLSyCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyCheckboxElement: {
        prototype: HTMLSyCheckboxElement;
        new (): HTMLSyCheckboxElement;
    };
    interface HTMLSyDividerElement extends Components.SyDivider, HTMLStencilElement {
    }
    var HTMLSyDividerElement: {
        prototype: HTMLSyDividerElement;
        new (): HTMLSyDividerElement;
    };
    interface HTMLSyDrawerElementEventMap {
        "opened": void;
        "closed": void;
    }
    interface HTMLSyDrawerElement extends Components.SyDrawer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyDrawerElementEventMap>(type: K, listener: (this: HTMLSyDrawerElement, ev: SyDrawerCustomEvent<HTMLSyDrawerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyDrawerElementEventMap>(type: K, listener: (this: HTMLSyDrawerElement, ev: SyDrawerCustomEvent<HTMLSyDrawerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyDrawerElement: {
        prototype: HTMLSyDrawerElement;
        new (): HTMLSyDrawerElement;
    };
    interface HTMLSyEmptyElement extends Components.SyEmpty, HTMLStencilElement {
    }
    var HTMLSyEmptyElement: {
        prototype: HTMLSyEmptyElement;
        new (): HTMLSyEmptyElement;
    };
    interface HTMLSyIconElementEventMap {
        "selected": { value: string };
    }
    interface HTMLSyIconElement extends Components.SyIcon, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyIconElementEventMap>(type: K, listener: (this: HTMLSyIconElement, ev: SyIconCustomEvent<HTMLSyIconElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyIconElementEventMap>(type: K, listener: (this: HTMLSyIconElement, ev: SyIconCustomEvent<HTMLSyIconElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyIconElement: {
        prototype: HTMLSyIconElement;
        new (): HTMLSyIconElement;
    };
    interface HTMLSyInputElementEventMap {
        "changed": { value: string; isValid: boolean; status: string };
        "blured": { value: string; isValid: boolean; status: string };
        "focused": { value: string; isValid: boolean; status: string };
    }
    interface HTMLSyInputElement extends Components.SyInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyInputElementEventMap>(type: K, listener: (this: HTMLSyInputElement, ev: SyInputCustomEvent<HTMLSyInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyInputElementEventMap>(type: K, listener: (this: HTMLSyInputElement, ev: SyInputCustomEvent<HTMLSyInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyInputElement: {
        prototype: HTMLSyInputElement;
        new (): HTMLSyInputElement;
    };
    /**
     * 팝오버 컴포넌트 - 다른 요소에 부가 정보를 표시하는 오버레이 요소
     * 마우스 호버, 클릭, 포커스 등의 트리거로 활성화됩니다.
     */
    interface HTMLSyPopoverElement extends Components.SyPopover, HTMLStencilElement {
    }
    var HTMLSyPopoverElement: {
        prototype: HTMLSyPopoverElement;
        new (): HTMLSyPopoverElement;
    };
    interface HTMLSySpinnerElement extends Components.SySpinner, HTMLStencilElement {
    }
    var HTMLSySpinnerElement: {
        prototype: HTMLSySpinnerElement;
        new (): HTMLSySpinnerElement;
    };
    interface HTMLSySplitPanelElementEventMap {
        "horizontalChanged": {
    leftRatio: number;
    rightRatio: number;
  };
        "verticalChanged": {
    topRatio: number;
    bottomRatio: number;
  };
    }
    interface HTMLSySplitPanelElement extends Components.SySplitPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSySplitPanelElementEventMap>(type: K, listener: (this: HTMLSySplitPanelElement, ev: SySplitPanelCustomEvent<HTMLSySplitPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSySplitPanelElementEventMap>(type: K, listener: (this: HTMLSySplitPanelElement, ev: SySplitPanelCustomEvent<HTMLSySplitPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSySplitPanelElement: {
        prototype: HTMLSySplitPanelElement;
        new (): HTMLSySplitPanelElement;
    };
    interface HTMLSySwitchElementEventMap {
        "changed": boolean;
    }
    interface HTMLSySwitchElement extends Components.SySwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSySwitchElementEventMap>(type: K, listener: (this: HTMLSySwitchElement, ev: SySwitchCustomEvent<HTMLSySwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSySwitchElementEventMap>(type: K, listener: (this: HTMLSySwitchElement, ev: SySwitchCustomEvent<HTMLSySwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSySwitchElement: {
        prototype: HTMLSySwitchElement;
        new (): HTMLSySwitchElement;
    };
    interface HTMLSyTagElementEventMap {
        "selected": { tag: HTMLElement };
        "removed": { tag: HTMLElement };
    }
    interface HTMLSyTagElement extends Components.SyTag, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyTagElementEventMap>(type: K, listener: (this: HTMLSyTagElement, ev: SyTagCustomEvent<HTMLSyTagElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyTagElementEventMap>(type: K, listener: (this: HTMLSyTagElement, ev: SyTagCustomEvent<HTMLSyTagElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyTagElement: {
        prototype: HTMLSyTagElement;
        new (): HTMLSyTagElement;
    };
    interface HTMLSyTextareaElementEventMap {
        "changed": { value: string; length: number; isValid: boolean; status: string };
        "blured": { value: string; isValid: boolean; status: string };
        "focused": { value: string; isValid: boolean; status: string };
    }
    interface HTMLSyTextareaElement extends Components.SyTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyTextareaElementEventMap>(type: K, listener: (this: HTMLSyTextareaElement, ev: SyTextareaCustomEvent<HTMLSyTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyTextareaElementEventMap>(type: K, listener: (this: HTMLSyTextareaElement, ev: SyTextareaCustomEvent<HTMLSyTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyTextareaElement: {
        prototype: HTMLSyTextareaElement;
        new (): HTMLSyTextareaElement;
    };
    interface HTMLSyTooltipElement extends Components.SyTooltip, HTMLStencilElement {
    }
    var HTMLSyTooltipElement: {
        prototype: HTMLSyTooltipElement;
        new (): HTMLSyTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "sy-avatar": HTMLSyAvatarElement;
        "sy-badge": HTMLSyBadgeElement;
        "sy-banner-messsage": HTMLSyBannerMesssageElement;
        "sy-breadcrumb": HTMLSyBreadcrumbElement;
        "sy-breadcrumb-item": HTMLSyBreadcrumbItemElement;
        "sy-button": HTMLSyButtonElement;
        "sy-button-group": HTMLSyButtonGroupElement;
        "sy-checkbox": HTMLSyCheckboxElement;
        "sy-divider": HTMLSyDividerElement;
        "sy-drawer": HTMLSyDrawerElement;
        "sy-empty": HTMLSyEmptyElement;
        "sy-icon": HTMLSyIconElement;
        "sy-input": HTMLSyInputElement;
        "sy-popover": HTMLSyPopoverElement;
        "sy-spinner": HTMLSySpinnerElement;
        "sy-split-panel": HTMLSySplitPanelElement;
        "sy-switch": HTMLSySwitchElement;
        "sy-tag": HTMLSyTagElement;
        "sy-textarea": HTMLSyTextareaElement;
        "sy-tooltip": HTMLSyTooltipElement;
    }
}
declare namespace LocalJSX {
    interface SyAvatar {
        /**
          * @default false
         */
        "clickable"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "icon"?: string;
        /**
          * @default ''
         */
        "image"?: string;
        /**
          * @default ''
         */
        "letter"?: string;
        "onDisableStatus"?: (event: SyAvatarCustomEvent<{ disabled: boolean }>) => void;
        "onSelected"?: (event: SyAvatarCustomEvent<{
    letter: string;
    text: string;
    icon: string;
    image: string;
  }>) => void;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default ''
         */
        "text"?: string;
        /**
          * @default ''
         */
        "tooltipContent"?: string;
        /**
          * @default "lightgray"
         */
        "variant"?: "lightgray"| "red" | "orange" | "yellow" | "lime" | "green" | "teal" | "blue" | "purple" | "magenta" | "darkgray";
    }
    interface SyBadge {
        /**
          * @default false
         */
        "dot"?: boolean;
        /**
          * @default false
         */
        "hidden"?: boolean;
        /**
          * @default Infinity
         */
        "overflowCount"?: number;
        /**
          * @default 'topRight'
         */
        "position"?: 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight';
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium';
        /**
          * @default false
         */
        "standalone"?: boolean;
        /**
          * @default 0
         */
        "value"?: number;
        /**
          * @default 'red'
         */
        "variant"?: 'red' | 'yellow' | 'green' | 'blue' | 'gray';
    }
    interface SyBannerMesssage {
        /**
          * @default false
         */
        "closable"?: boolean;
        /**
          * @default ''
         */
        "header"?: string;
        /**
          * @default ''
         */
        "message"?: string;
        /**
          * @default ''
         */
        "neutralIcon"?: string;
        /**
          * @default false
         */
        "showIcon"?: boolean;
        /**
          * @default 'info'
         */
        "variant"?: 'info' | 'success' | 'warning' | 'error' | 'neutral';
    }
    interface SyBreadcrumb {
        /**
          * @default 'slash'
         */
        "separator"?: 'slash' | 'arrow';
    }
    interface SyBreadcrumbItem {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "isLast"?: boolean;
        "onSelected"?: (event: SyBreadcrumbItemCustomEvent<HTMLSyBreadcrumbItemElement>) => void;
        /**
          * @default 'slash'
         */
        "parentSeparator"?: 'slash' | 'arrow';
        "separator"?: 'slash' | 'arrow';
    }
    interface SyButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "formnovalidate"?: boolean;
        /**
          * @default false
         */
        "justified"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'primary' | 'secondary' | 'borderless';
    }
    interface SyButtonGroup {
        /**
          * @default false
         */
        "vertical"?: boolean;
    }
    interface SyCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * @default ''
         */
        "name"?: string;
        "onBlured"?: (event: SyCheckboxCustomEvent<boolean>) => void;
        "onChanged"?: (event: SyCheckboxCustomEvent<{ value: boolean; isValid: boolean; checked: boolean; indeterminate: boolean; }>) => void;
        "onFocused"?: (event: SyCheckboxCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "titleText"?: string;
    }
    interface SyDivider {
        /**
          * @default 'horizontal'
         */
        "type"?: 'horizontal' | 'vertical';
    }
    interface SyDrawer {
        /**
          * @default false
         */
        "closable"?: boolean;
        /**
          * @default 100
         */
        "customSize"?: number;
        /**
          * @default false
         */
        "maskless"?: boolean;
        "onClosed"?: (event: SyDrawerCustomEvent<void>) => void;
        "onOpened"?: (event: SyDrawerCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'right'
         */
        "position"?: 'top' | 'left' | 'right' | 'bottom';
        /**
          * @default false
         */
        "preventClose"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | 'custom';
    }
    interface SyEmpty {
        /**
          * Empty 컴포넌트에 표시될 설명 텍스트입니다. Lit의
          * @property에 해당합니다.
         */
        "description"?: string;
    }
    interface SyIcon {
        "onSelected"?: (event: SyIconCustomEvent<{ value: string }>) => void;
        "path"?: string;
        /**
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge' | 'xxxlarge';
    }
    interface SyInput {
        /**
          * @default false
         */
        "autofocus"?: boolean;
        /**
          * @default false
         */
        "borderless"?: boolean;
        /**
          * @default false
         */
        "clearable"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "label"?: string;
        "max"?: number;
        "min"?: number;
        /**
          * @default ""
         */
        "name"?: string;
        /**
          * @default false
         */
        "noNativeValidity"?: boolean;
        "onBlured"?: (event: SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>) => void;
        "onChanged"?: (event: SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>) => void;
        "onFocused"?: (event: SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default "medium"
         */
        "size"?: "small" | "medium" | "large";
        /**
          * @default 'default'
         */
        "status"?: 'default' | 'warning' | 'error' | 'success';
        /**
          * @default ""
         */
        "value"?: string;
        /**
          * @default "text"
         */
        "variant"?: "password" | "search" | "text";
    }
    /**
     * 팝오버 컴포넌트 - 다른 요소에 부가 정보를 표시하는 오버레이 요소
     * 마우스 호버, 클릭, 포커스 등의 트리거로 활성화됩니다.
     */
    interface SyPopover {
        /**
          * @default false
         */
        "arrow"?: boolean;
        /**
          * @default 100
         */
        "closedelay"?: number;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 0
         */
        "opendelay"?: number;
        /**
          * @default 'bottom'
         */
        "position"?: 'top' | 'bottom' | 'left' | 'right' | 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight' | 'leftTop' | 'leftBottom' | 'rightTop' | 'rightBottom';
        /**
          * @default false
         */
        "sticky"?: boolean;
        /**
          * @default 'hover'
         */
        "trigger"?: 'hover' | 'click' | 'focus' | 'null';
    }
    interface SySpinner {
        /**
          * @default 0
         */
        "delay"?: number;
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default false
         */
        "hidden"?: boolean;
        /**
          * @default false
         */
        "inline"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | 'xlarge';
    }
    interface SySplitPanel {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "hideDivider"?: boolean;
        /**
          * @default 0
         */
        "minRatio"?: number;
        "onHorizontalChanged"?: (event: SySplitPanelCustomEvent<{
    leftRatio: number;
    rightRatio: number;
  }>) => void;
        "onVerticalChanged"?: (event: SySplitPanelCustomEvent<{
    topRatio: number;
    bottomRatio: number;
  }>) => void;
        /**
          * @default 50
         */
        "ratio"?: number;
        /**
          * @default 'horizontal'
         */
        "type"?: 'horizontal' | 'vertical';
    }
    interface SySwitch {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label"?: string;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default ''
         */
        "name"?: string;
        "onChanged"?: (event: SySwitchCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium';
    }
    interface SyTag {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onRemoved"?: (event: SyTagCustomEvent<{ tag: HTMLElement }>) => void;
        "onSelected"?: (event: SyTagCustomEvent<{ tag: HTMLElement }>) => void;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "removable"?: boolean;
        /**
          * @default false
         */
        "rounded"?: boolean;
        /**
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'gray'
         */
        "variant"?: 'gray' | 'purple' | 'blue' | 'green' | 'cyan' | 'yellow' | 'orange' | 'red';
    }
    interface SyTextarea {
        /**
          * @default false
         */
        "autofocus"?: boolean;
        /**
          * @default false
         */
        "borderless"?: boolean;
        /**
          * @default false
         */
        "clearable"?: boolean;
        /**
          * @default false
         */
        "counter"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "label"?: string;
        /**
          * @default Number.MAX_SAFE_INTEGER
         */
        "max"?: number;
        /**
          * @default 0
         */
        "min"?: number;
        /**
          * @default ""
         */
        "name"?: string;
        /**
          * @default false
         */
        "noNativeValidity"?: boolean;
        "onBlured"?: (event: SyTextareaCustomEvent<{ value: string; isValid: boolean; status: string }>) => void;
        "onChanged"?: (event: SyTextareaCustomEvent<{ value: string; length: number; isValid: boolean; status: string }>) => void;
        "onFocused"?: (event: SyTextareaCustomEvent<{ value: string; isValid: boolean; status: string }>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default "none"
         */
        "resize"?: "none" | "horizontal" | "vertical" | "both";
        /**
          * @default 4
         */
        "rows"?: number;
        /**
          * @default "medium"
         */
        "size"?: "small" | "medium" | "large";
        /**
          * @default 'default'
         */
        "status"?: 'default' | 'warning' | 'error' | 'success';
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface SyTooltip {
        /**
          * @default 0
         */
        "closedelay"?: number;
        /**
          * @default ''
         */
        "content"?: string;
        /**
          * @default false
         */
        "hideArrow"?: boolean;
        /**
          * @default null
         */
        "maxWidth"?: number | null;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 0
         */
        "opendelay"?: number;
        /**
          * @default 'top'
         */
        "position"?: 'top' | 'topLeft' | 'topRight' | 'right' | 'rightTop' | 'rightBottom' | 'bottom' | 'bottomLeft' | 'bottomRight' | 'left' | 'leftTop' | 'leftBottom';
        /**
          * @default 'hover'
         */
        "trigger"?: 'hover' | 'click' | 'focus' | 'none';
    }
    interface IntrinsicElements {
        "sy-avatar": SyAvatar;
        "sy-badge": SyBadge;
        "sy-banner-messsage": SyBannerMesssage;
        "sy-breadcrumb": SyBreadcrumb;
        "sy-breadcrumb-item": SyBreadcrumbItem;
        "sy-button": SyButton;
        "sy-button-group": SyButtonGroup;
        "sy-checkbox": SyCheckbox;
        "sy-divider": SyDivider;
        "sy-drawer": SyDrawer;
        "sy-empty": SyEmpty;
        "sy-icon": SyIcon;
        "sy-input": SyInput;
        "sy-popover": SyPopover;
        "sy-spinner": SySpinner;
        "sy-split-panel": SySplitPanel;
        "sy-switch": SySwitch;
        "sy-tag": SyTag;
        "sy-textarea": SyTextarea;
        "sy-tooltip": SyTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-avatar": LocalJSX.SyAvatar & JSXBase.HTMLAttributes<HTMLSyAvatarElement>;
            "sy-badge": LocalJSX.SyBadge & JSXBase.HTMLAttributes<HTMLSyBadgeElement>;
            "sy-banner-messsage": LocalJSX.SyBannerMesssage & JSXBase.HTMLAttributes<HTMLSyBannerMesssageElement>;
            "sy-breadcrumb": LocalJSX.SyBreadcrumb & JSXBase.HTMLAttributes<HTMLSyBreadcrumbElement>;
            "sy-breadcrumb-item": LocalJSX.SyBreadcrumbItem & JSXBase.HTMLAttributes<HTMLSyBreadcrumbItemElement>;
            "sy-button": LocalJSX.SyButton & JSXBase.HTMLAttributes<HTMLSyButtonElement>;
            "sy-button-group": LocalJSX.SyButtonGroup & JSXBase.HTMLAttributes<HTMLSyButtonGroupElement>;
            "sy-checkbox": LocalJSX.SyCheckbox & JSXBase.HTMLAttributes<HTMLSyCheckboxElement>;
            "sy-divider": LocalJSX.SyDivider & JSXBase.HTMLAttributes<HTMLSyDividerElement>;
            "sy-drawer": LocalJSX.SyDrawer & JSXBase.HTMLAttributes<HTMLSyDrawerElement>;
            "sy-empty": LocalJSX.SyEmpty & JSXBase.HTMLAttributes<HTMLSyEmptyElement>;
            "sy-icon": LocalJSX.SyIcon & JSXBase.HTMLAttributes<HTMLSyIconElement>;
            "sy-input": LocalJSX.SyInput & JSXBase.HTMLAttributes<HTMLSyInputElement>;
            /**
             * 팝오버 컴포넌트 - 다른 요소에 부가 정보를 표시하는 오버레이 요소
             * 마우스 호버, 클릭, 포커스 등의 트리거로 활성화됩니다.
             */
            "sy-popover": LocalJSX.SyPopover & JSXBase.HTMLAttributes<HTMLSyPopoverElement>;
            "sy-spinner": LocalJSX.SySpinner & JSXBase.HTMLAttributes<HTMLSySpinnerElement>;
            "sy-split-panel": LocalJSX.SySplitPanel & JSXBase.HTMLAttributes<HTMLSySplitPanelElement>;
            "sy-switch": LocalJSX.SySwitch & JSXBase.HTMLAttributes<HTMLSySwitchElement>;
            "sy-tag": LocalJSX.SyTag & JSXBase.HTMLAttributes<HTMLSyTagElement>;
            "sy-textarea": LocalJSX.SyTextarea & JSXBase.HTMLAttributes<HTMLSyTextareaElement>;
            "sy-tooltip": LocalJSX.SyTooltip & JSXBase.HTMLAttributes<HTMLSyTooltipElement>;
        }
    }
}
