/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SyButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "formnovalidate": boolean;
        /**
          * @default false
         */
        "justified": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        "setBlur": () => Promise<void>;
        "setClick": () => Promise<void>;
        "setFocus": () => Promise<void>;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'primary' | 'secondary' | 'borderless';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSyButtonElement extends Components.SyButton, HTMLStencilElement {
    }
    var HTMLSyButtonElement: {
        prototype: HTMLSyButtonElement;
        new (): HTMLSyButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sy-button": HTMLSyButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SyButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "formnovalidate"?: boolean;
        /**
          * @default false
         */
        "justified"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'primary' | 'secondary' | 'borderless';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sy-button": SyButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sy-button": LocalJSX.SyButton & JSXBase.HTMLAttributes<HTMLSyButtonElement>;
        }
    }
}
