/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SyButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "formnovalidate": boolean;
        /**
          * @default false
         */
        "justified": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        "setBlur": () => Promise<void>;
        "setClick": () => Promise<void>;
        "setFocus": () => Promise<void>;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'primary' | 'secondary' | 'borderless';
    }
    interface SyIcon {
        "path"?: string;
        /**
          * @default false
         */
        "selectable": boolean;
        /**
          * @default 'medium'
         */
        "size": 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge' | 'xxxlarge';
    }
}
export interface SyIconCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSyIconElement;
}
declare global {
    interface HTMLSyButtonElement extends Components.SyButton, HTMLStencilElement {
    }
    var HTMLSyButtonElement: {
        prototype: HTMLSyButtonElement;
        new (): HTMLSyButtonElement;
    };
    interface HTMLSyIconElementEventMap {
        "selected": { value: string };
    }
    interface HTMLSyIconElement extends Components.SyIcon, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSyIconElementEventMap>(type: K, listener: (this: HTMLSyIconElement, ev: SyIconCustomEvent<HTMLSyIconElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSyIconElementEventMap>(type: K, listener: (this: HTMLSyIconElement, ev: SyIconCustomEvent<HTMLSyIconElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSyIconElement: {
        prototype: HTMLSyIconElement;
        new (): HTMLSyIconElement;
    };
    interface HTMLElementTagNameMap {
        "sy-button": HTMLSyButtonElement;
        "sy-icon": HTMLSyIconElement;
    }
}
declare namespace LocalJSX {
    interface SyButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "formnovalidate"?: boolean;
        /**
          * @default false
         */
        "justified"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'primary' | 'secondary' | 'borderless';
    }
    interface SyIcon {
        "onSelected"?: (event: SyIconCustomEvent<{ value: string }>) => void;
        "path"?: string;
        /**
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge' | 'xxxlarge';
    }
    interface IntrinsicElements {
        "sy-button": SyButton;
        "sy-icon": SyIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-button": LocalJSX.SyButton & JSXBase.HTMLAttributes<HTMLSyButtonElement>;
            "sy-icon": LocalJSX.SyIcon & JSXBase.HTMLAttributes<HTMLSyIconElement>;
        }
    }
}
