'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CollapsePanelChangeDetail, type ModelessPositionChangedDetail, type SyAutocompleteCustomEvent, type SyAutocompleteOptionCustomEvent, type SyAvatarCustomEvent, type SyAvatarGroupCustomEvent, type SyBreadcrumbItemCustomEvent, type SyCalendarCustomEvent, type SyCheckboxCustomEvent, type SyCollapsePanelCustomEvent, type SyColorpickerContentCustomEvent, type SyColorpickerCustomEvent, type SyDateCalendarCustomEvent, type SyDateTimeCalendarCustomEvent, type SyDatepickerCustomEvent, type SyDrawerCustomEvent, type SyDropdownCustomEvent, type SyGlobalHeaderCustomEvent, type SyIconCustomEvent, type SyInlineMessageCustomEvent, type SyInputCustomEvent, type SyInputNumberCustomEvent, type SyMenuCustomEvent, type SyMenuItemCustomEvent, type SyModalCustomEvent, type SyModelessCustomEvent, type SyOptionCustomEvent, type SyPaginationCustomEvent, type SyPopconfirmCustomEvent, type SyRadioButtonCustomEvent, type SyRadioCustomEvent, type SyRadioGroupCustomEvent, type SyRangeCalendarCustomEvent, type SySelectCustomEvent, type SySplitPanelCustomEvent, type SySwitchCustomEvent, type SyTabCustomEvent, type SyTabGroupCustomEvent, type SyTagCustomEvent, type SyTextareaCustomEvent, type SyTimepickerCustomEvent, type SyTreeCustomEvent, type SyTreeItemCustomEvent, type SyTreeSelectCustomEvent, type TreeNode } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyAutocompleteOption as SyAutocompleteOptionElement, defineCustomElement as defineSyAutocompleteOption } from "@dc/synergy/components/sy-autocomplete-option.js";
import { SyAutocomplete as SyAutocompleteElement, defineCustomElement as defineSyAutocomplete } from "@dc/synergy/components/sy-autocomplete.js";
import { SyAvatarGroup as SyAvatarGroupElement, defineCustomElement as defineSyAvatarGroup } from "@dc/synergy/components/sy-avatar-group.js";
import { SyAvatar as SyAvatarElement, defineCustomElement as defineSyAvatar } from "@dc/synergy/components/sy-avatar.js";
import { SyBadge as SyBadgeElement, defineCustomElement as defineSyBadge } from "@dc/synergy/components/sy-badge.js";
import { SyBannerMessage as SyBannerMessageElement, defineCustomElement as defineSyBannerMessage } from "@dc/synergy/components/sy-banner-message.js";
import { SyBreadcrumbItem as SyBreadcrumbItemElement, defineCustomElement as defineSyBreadcrumbItem } from "@dc/synergy/components/sy-breadcrumb-item.js";
import { SyBreadcrumb as SyBreadcrumbElement, defineCustomElement as defineSyBreadcrumb } from "@dc/synergy/components/sy-breadcrumb.js";
import { SyButtonGroup as SyButtonGroupElement, defineCustomElement as defineSyButtonGroup } from "@dc/synergy/components/sy-button-group.js";
import { SyButton as SyButtonElement, defineCustomElement as defineSyButton } from "@dc/synergy/components/sy-button.js";
import { SyCalendar as SyCalendarElement, defineCustomElement as defineSyCalendar } from "@dc/synergy/components/sy-calendar.js";
import { SyCard as SyCardElement, defineCustomElement as defineSyCard } from "@dc/synergy/components/sy-card.js";
import { SyCheckbox as SyCheckboxElement, defineCustomElement as defineSyCheckbox } from "@dc/synergy/components/sy-checkbox.js";
import { SyCollapsePanel as SyCollapsePanelElement, defineCustomElement as defineSyCollapsePanel } from "@dc/synergy/components/sy-collapse-panel.js";
import { SyCollapse as SyCollapseElement, defineCustomElement as defineSyCollapse } from "@dc/synergy/components/sy-collapse.js";
import { SyColorpickerContent as SyColorpickerContentElement, defineCustomElement as defineSyColorpickerContent } from "@dc/synergy/components/sy-colorpicker-content.js";
import { SyColorpicker as SyColorpickerElement, defineCustomElement as defineSyColorpicker } from "@dc/synergy/components/sy-colorpicker.js";
import { SyDateCalendar as SyDateCalendarElement, defineCustomElement as defineSyDateCalendar } from "@dc/synergy/components/sy-date-calendar.js";
import { SyDateTimeCalendar as SyDateTimeCalendarElement, defineCustomElement as defineSyDateTimeCalendar } from "@dc/synergy/components/sy-date-time-calendar.js";
import { SyDatepicker as SyDatepickerElement, defineCustomElement as defineSyDatepicker } from "@dc/synergy/components/sy-datepicker.js";
import { SyDivider as SyDividerElement, defineCustomElement as defineSyDivider } from "@dc/synergy/components/sy-divider.js";
import { SyDrawer as SyDrawerElement, defineCustomElement as defineSyDrawer } from "@dc/synergy/components/sy-drawer.js";
import { SyDropdown as SyDropdownElement, defineCustomElement as defineSyDropdown } from "@dc/synergy/components/sy-dropdown.js";
import { SyEmpty as SyEmptyElement, defineCustomElement as defineSyEmpty } from "@dc/synergy/components/sy-empty.js";
import { SyFlex as SyFlexElement, defineCustomElement as defineSyFlex } from "@dc/synergy/components/sy-flex.js";
import { SyGlobalHeader as SyGlobalHeaderElement, defineCustomElement as defineSyGlobalHeader } from "@dc/synergy/components/sy-global-header.js";
import { SyIcon as SyIconElement, defineCustomElement as defineSyIcon } from "@dc/synergy/components/sy-icon.js";
import { SyInlineMessage as SyInlineMessageElement, defineCustomElement as defineSyInlineMessage } from "@dc/synergy/components/sy-inline-message.js";
import { SyInputNumber as SyInputNumberElement, defineCustomElement as defineSyInputNumber } from "@dc/synergy/components/sy-input-number.js";
import { SyInput as SyInputElement, defineCustomElement as defineSyInput } from "@dc/synergy/components/sy-input.js";
import { SyLabel as SyLabelElement, defineCustomElement as defineSyLabel } from "@dc/synergy/components/sy-label.js";
import { SyMenuGroup as SyMenuGroupElement, defineCustomElement as defineSyMenuGroup } from "@dc/synergy/components/sy-menu-group.js";
import { SyMenuItem as SyMenuItemElement, defineCustomElement as defineSyMenuItem } from "@dc/synergy/components/sy-menu-item.js";
import { SyMenuSub as SyMenuSubElement, defineCustomElement as defineSyMenuSub } from "@dc/synergy/components/sy-menu-sub.js";
import { SyMenu as SyMenuElement, defineCustomElement as defineSyMenu } from "@dc/synergy/components/sy-menu.js";
import { SyModal as SyModalElement, defineCustomElement as defineSyModal } from "@dc/synergy/components/sy-modal.js";
import { SyModelessGroup as SyModelessGroupElement, defineCustomElement as defineSyModelessGroup } from "@dc/synergy/components/sy-modeless-group.js";
import { SyModeless as SyModelessElement, defineCustomElement as defineSyModeless } from "@dc/synergy/components/sy-modeless.js";
import { SyNavGroup as SyNavGroupElement, defineCustomElement as defineSyNavGroup } from "@dc/synergy/components/sy-nav-group.js";
import { SyNavItem as SyNavItemElement, defineCustomElement as defineSyNavItem } from "@dc/synergy/components/sy-nav-item.js";
import { SyNavSub as SyNavSubElement, defineCustomElement as defineSyNavSub } from "@dc/synergy/components/sy-nav-sub.js";
import { SyNav as SyNavElement, defineCustomElement as defineSyNav } from "@dc/synergy/components/sy-nav.js";
import { SyOption as SyOptionElement, defineCustomElement as defineSyOption } from "@dc/synergy/components/sy-option.js";
import { SyPagination as SyPaginationElement, defineCustomElement as defineSyPagination } from "@dc/synergy/components/sy-pagination.js";
import { SyPopconfirm as SyPopconfirmElement, defineCustomElement as defineSyPopconfirm } from "@dc/synergy/components/sy-popconfirm.js";
import { SyPopover as SyPopoverElement, defineCustomElement as defineSyPopover } from "@dc/synergy/components/sy-popover.js";
import { SyProgressBar as SyProgressBarElement, defineCustomElement as defineSyProgressBar } from "@dc/synergy/components/sy-progress-bar.js";
import { SyProgressCircular as SyProgressCircularElement, defineCustomElement as defineSyProgressCircular } from "@dc/synergy/components/sy-progress-circular.js";
import { SyRadioButton as SyRadioButtonElement, defineCustomElement as defineSyRadioButton } from "@dc/synergy/components/sy-radio-button.js";
import { SyRadioGroup as SyRadioGroupElement, defineCustomElement as defineSyRadioGroup } from "@dc/synergy/components/sy-radio-group.js";
import { SyRadio as SyRadioElement, defineCustomElement as defineSyRadio } from "@dc/synergy/components/sy-radio.js";
import { SyRangeCalendar as SyRangeCalendarElement, defineCustomElement as defineSyRangeCalendar } from "@dc/synergy/components/sy-range-calendar.js";
import { SySelect as SySelectElement, defineCustomElement as defineSySelect } from "@dc/synergy/components/sy-select.js";
import { SySkeleton as SySkeletonElement, defineCustomElement as defineSySkeleton } from "@dc/synergy/components/sy-skeleton.js";
import { SySlider as SySliderElement, defineCustomElement as defineSySlider } from "@dc/synergy/components/sy-slider.js";
import { SySpinner as SySpinnerElement, defineCustomElement as defineSySpinner } from "@dc/synergy/components/sy-spinner.js";
import { SySplitPanel as SySplitPanelElement, defineCustomElement as defineSySplitPanel } from "@dc/synergy/components/sy-split-panel.js";
import { SyStep as SyStepElement, defineCustomElement as defineSyStep } from "@dc/synergy/components/sy-step.js";
import { SySteps as SyStepsElement, defineCustomElement as defineSySteps } from "@dc/synergy/components/sy-steps.js";
import { SySwitch as SySwitchElement, defineCustomElement as defineSySwitch } from "@dc/synergy/components/sy-switch.js";
import { SyTabContent as SyTabContentElement, defineCustomElement as defineSyTabContent } from "@dc/synergy/components/sy-tab-content.js";
import { SyTabGroup as SyTabGroupElement, defineCustomElement as defineSyTabGroup } from "@dc/synergy/components/sy-tab-group.js";
import { SyTab as SyTabElement, defineCustomElement as defineSyTab } from "@dc/synergy/components/sy-tab.js";
import { SyTag as SyTagElement, defineCustomElement as defineSyTag } from "@dc/synergy/components/sy-tag.js";
import { SyTextarea as SyTextareaElement, defineCustomElement as defineSyTextarea } from "@dc/synergy/components/sy-textarea.js";
import { SyTimepicker as SyTimepickerElement, defineCustomElement as defineSyTimepicker } from "@dc/synergy/components/sy-timepicker.js";
import { SyToastItem as SyToastItemElement, defineCustomElement as defineSyToastItem } from "@dc/synergy/components/sy-toast-item.js";
import { SyToast as SyToastElement, defineCustomElement as defineSyToast } from "@dc/synergy/components/sy-toast.js";
import { SyTooltip as SyTooltipElement, defineCustomElement as defineSyTooltip } from "@dc/synergy/components/sy-tooltip.js";
import { SyTreeItem as SyTreeItemElement, defineCustomElement as defineSyTreeItem } from "@dc/synergy/components/sy-tree-item.js";
import { SyTreeSelect as SyTreeSelectElement, defineCustomElement as defineSyTreeSelect } from "@dc/synergy/components/sy-tree-select.js";
import { SyTree as SyTreeElement, defineCustomElement as defineSyTree } from "@dc/synergy/components/sy-tree.js";

export type SyAutocompleteEvents = {
    onChanged: EventName<SyAutocompleteCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onSelected: EventName<SyAutocompleteCustomEvent<{ value: string; isValid: boolean; status: string }>>
};

export const SyAutocomplete: StencilReactComponent<SyAutocompleteElement, SyAutocompleteEvents, JSX.SyAutocomplete> = /*@__PURE__*/ createComponent<SyAutocompleteElement, SyAutocompleteEvents, JSX.SyAutocomplete>({
    tagName: 'sy-autocomplete',
    elementClass: SyAutocompleteElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onSelected: 'selected'
    } as SyAutocompleteEvents,
    defineCustomElement: defineSyAutocomplete
});

export type SyAutocompleteOptionEvents = {
    onActiveChanged: EventName<SyAutocompleteOptionCustomEvent<number>>,
    onSelected: EventName<SyAutocompleteOptionCustomEvent<string>>
};

export const SyAutocompleteOption: StencilReactComponent<SyAutocompleteOptionElement, SyAutocompleteOptionEvents, JSX.SyAutocompleteOption> = /*@__PURE__*/ createComponent<SyAutocompleteOptionElement, SyAutocompleteOptionEvents, JSX.SyAutocompleteOption>({
    tagName: 'sy-autocomplete-option',
    elementClass: SyAutocompleteOptionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onActiveChanged: 'activeChanged',
        onSelected: 'selected'
    } as SyAutocompleteOptionEvents,
    defineCustomElement: defineSyAutocompleteOption
});

export type SyAvatarEvents = {
    onSelected: EventName<SyAvatarCustomEvent<{ letter: string; text: string; icon: string; image: string; }>>,
    onDisableStatus: EventName<SyAvatarCustomEvent<{ disabled: boolean }>>
};

export const SyAvatar: StencilReactComponent<SyAvatarElement, SyAvatarEvents, JSX.SyAvatar> = /*@__PURE__*/ createComponent<SyAvatarElement, SyAvatarEvents, JSX.SyAvatar>({
    tagName: 'sy-avatar',
    elementClass: SyAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onDisableStatus: 'disableStatus'
    } as SyAvatarEvents,
    defineCustomElement: defineSyAvatar
});

export type SyAvatarGroupEvents = { onSelected: EventName<SyAvatarGroupCustomEvent<{ letter: string; text: string; icon: string; image: string; }>> };

export const SyAvatarGroup: StencilReactComponent<SyAvatarGroupElement, SyAvatarGroupEvents, JSX.SyAvatarGroup> = /*@__PURE__*/ createComponent<SyAvatarGroupElement, SyAvatarGroupEvents, JSX.SyAvatarGroup>({
    tagName: 'sy-avatar-group',
    elementClass: SyAvatarGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyAvatarGroupEvents,
    defineCustomElement: defineSyAvatarGroup
});

export type SyBadgeEvents = NonNullable<unknown>;

export const SyBadge: StencilReactComponent<SyBadgeElement, SyBadgeEvents, JSX.SyBadge> = /*@__PURE__*/ createComponent<SyBadgeElement, SyBadgeEvents, JSX.SyBadge>({
    tagName: 'sy-badge',
    elementClass: SyBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyBadgeEvents,
    defineCustomElement: defineSyBadge
});

export type SyBannerMessageEvents = NonNullable<unknown>;

export const SyBannerMessage: StencilReactComponent<SyBannerMessageElement, SyBannerMessageEvents, JSX.SyBannerMessage> = /*@__PURE__*/ createComponent<SyBannerMessageElement, SyBannerMessageEvents, JSX.SyBannerMessage>({
    tagName: 'sy-banner-message',
    elementClass: SyBannerMessageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyBannerMessageEvents,
    defineCustomElement: defineSyBannerMessage
});

export type SyBreadcrumbEvents = NonNullable<unknown>;

export const SyBreadcrumb: StencilReactComponent<SyBreadcrumbElement, SyBreadcrumbEvents, JSX.SyBreadcrumb> = /*@__PURE__*/ createComponent<SyBreadcrumbElement, SyBreadcrumbEvents, JSX.SyBreadcrumb>({
    tagName: 'sy-breadcrumb',
    elementClass: SyBreadcrumbElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyBreadcrumbEvents,
    defineCustomElement: defineSyBreadcrumb
});

export type SyBreadcrumbItemEvents = { onSelected: EventName<SyBreadcrumbItemCustomEvent<HTMLSyBreadcrumbItemElement>> };

export const SyBreadcrumbItem: StencilReactComponent<SyBreadcrumbItemElement, SyBreadcrumbItemEvents, JSX.SyBreadcrumbItem> = /*@__PURE__*/ createComponent<SyBreadcrumbItemElement, SyBreadcrumbItemEvents, JSX.SyBreadcrumbItem>({
    tagName: 'sy-breadcrumb-item',
    elementClass: SyBreadcrumbItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyBreadcrumbItemEvents,
    defineCustomElement: defineSyBreadcrumbItem
});

export type SyButtonEvents = NonNullable<unknown>;

export const SyButton: StencilReactComponent<SyButtonElement, SyButtonEvents, JSX.SyButton> = /*@__PURE__*/ createComponent<SyButtonElement, SyButtonEvents, JSX.SyButton>({
    tagName: 'sy-button',
    elementClass: SyButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyButtonEvents,
    defineCustomElement: defineSyButton
});

export type SyButtonGroupEvents = NonNullable<unknown>;

export const SyButtonGroup: StencilReactComponent<SyButtonGroupElement, SyButtonGroupEvents, JSX.SyButtonGroup> = /*@__PURE__*/ createComponent<SyButtonGroupElement, SyButtonGroupEvents, JSX.SyButtonGroup>({
    tagName: 'sy-button-group',
    elementClass: SyButtonGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyButtonGroupEvents,
    defineCustomElement: defineSyButtonGroup
});

export type SyCalendarEvents = {
    onSelected: EventName<SyCalendarCustomEvent<any>>,
    onClosed: EventName<SyCalendarCustomEvent<any>>
};

export const SyCalendar: StencilReactComponent<SyCalendarElement, SyCalendarEvents, JSX.SyCalendar> = /*@__PURE__*/ createComponent<SyCalendarElement, SyCalendarEvents, JSX.SyCalendar>({
    tagName: 'sy-calendar',
    elementClass: SyCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onClosed: 'closed'
    } as SyCalendarEvents,
    defineCustomElement: defineSyCalendar
});

export type SyCardEvents = NonNullable<unknown>;

export const SyCard: StencilReactComponent<SyCardElement, SyCardEvents, JSX.SyCard> = /*@__PURE__*/ createComponent<SyCardElement, SyCardEvents, JSX.SyCard>({
    tagName: 'sy-card',
    elementClass: SyCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyCardEvents,
    defineCustomElement: defineSyCard
});

export type SyCheckboxEvents = {
    onChanged: EventName<SyCheckboxCustomEvent<{ value: boolean; isValid: boolean; checked: boolean; indeterminate: boolean }>>,
    onFocused: EventName<SyCheckboxCustomEvent<boolean>>,
    onBlured: EventName<SyCheckboxCustomEvent<boolean>>
};

export const SyCheckbox: StencilReactComponent<SyCheckboxElement, SyCheckboxEvents, JSX.SyCheckbox> = /*@__PURE__*/ createComponent<SyCheckboxElement, SyCheckboxEvents, JSX.SyCheckbox>({
    tagName: 'sy-checkbox',
    elementClass: SyCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onFocused: 'focused',
        onBlured: 'blured'
    } as SyCheckboxEvents,
    defineCustomElement: defineSyCheckbox
});

export type SyCollapseEvents = NonNullable<unknown>;

export const SyCollapse: StencilReactComponent<SyCollapseElement, SyCollapseEvents, JSX.SyCollapse> = /*@__PURE__*/ createComponent<SyCollapseElement, SyCollapseEvents, JSX.SyCollapse>({
    tagName: 'sy-collapse',
    elementClass: SyCollapseElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyCollapseEvents,
    defineCustomElement: defineSyCollapse
});

export type SyCollapsePanelEvents = { onChanged: EventName<SyCollapsePanelCustomEvent<CollapsePanelChangeDetail>> };

export const SyCollapsePanel: StencilReactComponent<SyCollapsePanelElement, SyCollapsePanelEvents, JSX.SyCollapsePanel> = /*@__PURE__*/ createComponent<SyCollapsePanelElement, SyCollapsePanelEvents, JSX.SyCollapsePanel>({
    tagName: 'sy-collapse-panel',
    elementClass: SyCollapsePanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SyCollapsePanelEvents,
    defineCustomElement: defineSyCollapsePanel
});

export type SyColorpickerEvents = { onChanged: EventName<SyColorpickerCustomEvent<{ value: string; format: string; opacity: number }>> };

export const SyColorpicker: StencilReactComponent<SyColorpickerElement, SyColorpickerEvents, JSX.SyColorpicker> = /*@__PURE__*/ createComponent<SyColorpickerElement, SyColorpickerEvents, JSX.SyColorpicker>({
    tagName: 'sy-colorpicker',
    elementClass: SyColorpickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SyColorpickerEvents,
    defineCustomElement: defineSyColorpicker
});

export type SyColorpickerContentEvents = { onColorChange: EventName<SyColorpickerContentCustomEvent<{ value: string; opacity: number; format: string }>> };

export const SyColorpickerContent: StencilReactComponent<SyColorpickerContentElement, SyColorpickerContentEvents, JSX.SyColorpickerContent> = /*@__PURE__*/ createComponent<SyColorpickerContentElement, SyColorpickerContentEvents, JSX.SyColorpickerContent>({
    tagName: 'sy-colorpicker-content',
    elementClass: SyColorpickerContentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onColorChange: 'colorChange' } as SyColorpickerContentEvents,
    defineCustomElement: defineSyColorpickerContent
});

export type SyDateCalendarEvents = {
    onChanged: EventName<SyDateCalendarCustomEvent<any>>,
    onSelected: EventName<SyDateCalendarCustomEvent<any>>,
    onEntered: EventName<SyDateCalendarCustomEvent<any>>,
    onModeChanged: EventName<SyDateCalendarCustomEvent<any>>
};

export const SyDateCalendar: StencilReactComponent<SyDateCalendarElement, SyDateCalendarEvents, JSX.SyDateCalendar> = /*@__PURE__*/ createComponent<SyDateCalendarElement, SyDateCalendarEvents, JSX.SyDateCalendar>({
    tagName: 'sy-date-calendar',
    elementClass: SyDateCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onSelected: 'selected',
        onEntered: 'entered',
        onModeChanged: 'mode-changed'
    } as SyDateCalendarEvents,
    defineCustomElement: defineSyDateCalendar
});

export type SyDateTimeCalendarEvents = { onSelected: EventName<SyDateTimeCalendarCustomEvent<any>> };

export const SyDateTimeCalendar: StencilReactComponent<SyDateTimeCalendarElement, SyDateTimeCalendarEvents, JSX.SyDateTimeCalendar> = /*@__PURE__*/ createComponent<SyDateTimeCalendarElement, SyDateTimeCalendarEvents, JSX.SyDateTimeCalendar>({
    tagName: 'sy-date-time-calendar',
    elementClass: SyDateTimeCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyDateTimeCalendarEvents,
    defineCustomElement: defineSyDateTimeCalendar
});

export type SyDatepickerEvents = {
    onChanged: EventName<SyDatepickerCustomEvent<any>>,
    onSelected: EventName<SyDatepickerCustomEvent<any>>
};

export const SyDatepicker: StencilReactComponent<SyDatepickerElement, SyDatepickerEvents, JSX.SyDatepicker> = /*@__PURE__*/ createComponent<SyDatepickerElement, SyDatepickerEvents, JSX.SyDatepicker>({
    tagName: 'sy-datepicker',
    elementClass: SyDatepickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onSelected: 'selected'
    } as SyDatepickerEvents,
    defineCustomElement: defineSyDatepicker
});

export type SyDividerEvents = NonNullable<unknown>;

export const SyDivider: StencilReactComponent<SyDividerElement, SyDividerEvents, JSX.SyDivider> = /*@__PURE__*/ createComponent<SyDividerElement, SyDividerEvents, JSX.SyDivider>({
    tagName: 'sy-divider',
    elementClass: SyDividerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyDividerEvents,
    defineCustomElement: defineSyDivider
});

export type SyDrawerEvents = {
    onOpened: EventName<SyDrawerCustomEvent<void>>,
    onClosed: EventName<SyDrawerCustomEvent<void>>
};

export const SyDrawer: StencilReactComponent<SyDrawerElement, SyDrawerEvents, JSX.SyDrawer> = /*@__PURE__*/ createComponent<SyDrawerElement, SyDrawerEvents, JSX.SyDrawer>({
    tagName: 'sy-drawer',
    elementClass: SyDrawerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpened: 'opened',
        onClosed: 'closed'
    } as SyDrawerEvents,
    defineCustomElement: defineSyDrawer
});

export type SyDropdownEvents = { onSelected: EventName<SyDropdownCustomEvent<any>> };

export const SyDropdown: StencilReactComponent<SyDropdownElement, SyDropdownEvents, JSX.SyDropdown> = /*@__PURE__*/ createComponent<SyDropdownElement, SyDropdownEvents, JSX.SyDropdown>({
    tagName: 'sy-dropdown',
    elementClass: SyDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyDropdownEvents,
    defineCustomElement: defineSyDropdown
});

export type SyEmptyEvents = NonNullable<unknown>;

export const SyEmpty: StencilReactComponent<SyEmptyElement, SyEmptyEvents, JSX.SyEmpty> = /*@__PURE__*/ createComponent<SyEmptyElement, SyEmptyEvents, JSX.SyEmpty>({
    tagName: 'sy-empty',
    elementClass: SyEmptyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyEmptyEvents,
    defineCustomElement: defineSyEmpty
});

export type SyFlexEvents = NonNullable<unknown>;

export const SyFlex: StencilReactComponent<SyFlexElement, SyFlexEvents, JSX.SyFlex> = /*@__PURE__*/ createComponent<SyFlexElement, SyFlexEvents, JSX.SyFlex>({
    tagName: 'sy-flex',
    elementClass: SyFlexElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyFlexEvents,
    defineCustomElement: defineSyFlex
});

export type SyGlobalHeaderEvents = {
    onChanged: EventName<SyGlobalHeaderCustomEvent<any>>,
    onActionClick: EventName<SyGlobalHeaderCustomEvent<any>>,
    onSelected: EventName<SyGlobalHeaderCustomEvent<any>>
};

export const SyGlobalHeader: StencilReactComponent<SyGlobalHeaderElement, SyGlobalHeaderEvents, JSX.SyGlobalHeader> = /*@__PURE__*/ createComponent<SyGlobalHeaderElement, SyGlobalHeaderEvents, JSX.SyGlobalHeader>({
    tagName: 'sy-global-header',
    elementClass: SyGlobalHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onActionClick: 'actionClick',
        onSelected: 'selected'
    } as SyGlobalHeaderEvents,
    defineCustomElement: defineSyGlobalHeader
});

export type SyIconEvents = { onSelected: EventName<SyIconCustomEvent<{ value: string }>> };

export const SyIcon: StencilReactComponent<SyIconElement, SyIconEvents, JSX.SyIcon> = /*@__PURE__*/ createComponent<SyIconElement, SyIconEvents, JSX.SyIcon>({
    tagName: 'sy-icon',
    elementClass: SyIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyIconEvents,
    defineCustomElement: defineSyIcon
});

export type SyInlineMessageEvents = {
    onActionClick: EventName<SyInlineMessageCustomEvent<MouseEvent>>,
    onBtnClick: EventName<SyInlineMessageCustomEvent<MouseEvent>>,
    onDismiss: EventName<SyInlineMessageCustomEvent<void>>
};

export const SyInlineMessage: StencilReactComponent<SyInlineMessageElement, SyInlineMessageEvents, JSX.SyInlineMessage> = /*@__PURE__*/ createComponent<SyInlineMessageElement, SyInlineMessageEvents, JSX.SyInlineMessage>({
    tagName: 'sy-inline-message',
    elementClass: SyInlineMessageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onActionClick: 'actionClick',
        onBtnClick: 'btnClick',
        onDismiss: 'dismiss'
    } as SyInlineMessageEvents,
    defineCustomElement: defineSyInlineMessage
});

export type SyInputEvents = {
    onChanged: EventName<SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onBlured: EventName<SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onFocused: EventName<SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onClear: EventName<SyInputCustomEvent<void>>
};

export const SyInput: StencilReactComponent<SyInputElement, SyInputEvents, JSX.SyInput> = /*@__PURE__*/ createComponent<SyInputElement, SyInputEvents, JSX.SyInput>({
    tagName: 'sy-input',
    elementClass: SyInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onBlured: 'blured',
        onFocused: 'focused',
        onClear: 'clear'
    } as SyInputEvents,
    defineCustomElement: defineSyInput
});

export type SyInputNumberEvents = {
    onChanged: EventName<SyInputNumberCustomEvent<{ value: number | null; isValid: boolean; status: string }>>,
    onBlured: EventName<SyInputNumberCustomEvent<{ value: number | null; isValid: boolean; status: string }>>,
    onFocused: EventName<SyInputNumberCustomEvent<{ value: number | null; isValid: boolean; status: string }>>
};

export const SyInputNumber: StencilReactComponent<SyInputNumberElement, SyInputNumberEvents, JSX.SyInputNumber> = /*@__PURE__*/ createComponent<SyInputNumberElement, SyInputNumberEvents, JSX.SyInputNumber>({
    tagName: 'sy-input-number',
    elementClass: SyInputNumberElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onBlured: 'blured',
        onFocused: 'focused'
    } as SyInputNumberEvents,
    defineCustomElement: defineSyInputNumber
});

export type SyLabelEvents = NonNullable<unknown>;

export const SyLabel: StencilReactComponent<SyLabelElement, SyLabelEvents, JSX.SyLabel> = /*@__PURE__*/ createComponent<SyLabelElement, SyLabelEvents, JSX.SyLabel>({
    tagName: 'sy-label',
    elementClass: SyLabelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyLabelEvents,
    defineCustomElement: defineSyLabel
});

export type SyMenuEvents = {
    onOpened: EventName<SyMenuCustomEvent<boolean>>,
    onItemSelected: EventName<SyMenuCustomEvent<any>>,
    onItemChecked: EventName<SyMenuCustomEvent<any>>
};

export const SyMenu: StencilReactComponent<SyMenuElement, SyMenuEvents, JSX.SyMenu> = /*@__PURE__*/ createComponent<SyMenuElement, SyMenuEvents, JSX.SyMenu>({
    tagName: 'sy-menu',
    elementClass: SyMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpened: 'opened',
        onItemSelected: 'itemSelected',
        onItemChecked: 'itemChecked'
    } as SyMenuEvents,
    defineCustomElement: defineSyMenu
});

export type SyMenuGroupEvents = NonNullable<unknown>;

export const SyMenuGroup: StencilReactComponent<SyMenuGroupElement, SyMenuGroupEvents, JSX.SyMenuGroup> = /*@__PURE__*/ createComponent<SyMenuGroupElement, SyMenuGroupEvents, JSX.SyMenuGroup>({
    tagName: 'sy-menu-group',
    elementClass: SyMenuGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyMenuGroupEvents,
    defineCustomElement: defineSyMenuGroup
});

export type SyMenuItemEvents = {
    onItemSelected: EventName<SyMenuItemCustomEvent<{ value: string; label: string }>>,
    onItemChecked: EventName<SyMenuItemCustomEvent<{ value: string; label: string; checked: boolean }>>
};

export const SyMenuItem: StencilReactComponent<SyMenuItemElement, SyMenuItemEvents, JSX.SyMenuItem> = /*@__PURE__*/ createComponent<SyMenuItemElement, SyMenuItemEvents, JSX.SyMenuItem>({
    tagName: 'sy-menu-item',
    elementClass: SyMenuItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onItemSelected: 'itemSelected',
        onItemChecked: 'itemChecked'
    } as SyMenuItemEvents,
    defineCustomElement: defineSyMenuItem
});

export type SyMenuSubEvents = NonNullable<unknown>;

export const SyMenuSub: StencilReactComponent<SyMenuSubElement, SyMenuSubEvents, JSX.SyMenuSub> = /*@__PURE__*/ createComponent<SyMenuSubElement, SyMenuSubEvents, JSX.SyMenuSub>({
    tagName: 'sy-menu-sub',
    elementClass: SyMenuSubElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyMenuSubEvents,
    defineCustomElement: defineSyMenuSub
});

export type SyModalEvents = { onClosed: EventName<SyModalCustomEvent<{ event: 'ok' | 'cancel' | 'close'; value: any; maximized: boolean; position: { top: string; left: string }; }>> };

export const SyModal: StencilReactComponent<SyModalElement, SyModalEvents, JSX.SyModal> = /*@__PURE__*/ createComponent<SyModalElement, SyModalEvents, JSX.SyModal>({
    tagName: 'sy-modal',
    elementClass: SyModalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onClosed: 'closed' } as SyModalEvents,
    defineCustomElement: defineSyModal
});

export type SyModelessEvents = {
    onClosed: EventName<SyModelessCustomEvent<{ id: string }>>,
    onStatusChanged: EventName<SyModelessCustomEvent<{ id: string; status: string }>>,
    onPositionChanged: EventName<SyModelessCustomEvent<ModelessPositionChangedDetail>>
};

export const SyModeless: StencilReactComponent<SyModelessElement, SyModelessEvents, JSX.SyModeless> = /*@__PURE__*/ createComponent<SyModelessElement, SyModelessEvents, JSX.SyModeless>({
    tagName: 'sy-modeless',
    elementClass: SyModelessElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onClosed: 'closed',
        onStatusChanged: 'statusChanged',
        onPositionChanged: 'positionChanged'
    } as SyModelessEvents,
    defineCustomElement: defineSyModeless
});

export type SyModelessGroupEvents = NonNullable<unknown>;

export const SyModelessGroup: StencilReactComponent<SyModelessGroupElement, SyModelessGroupEvents, JSX.SyModelessGroup> = /*@__PURE__*/ createComponent<SyModelessGroupElement, SyModelessGroupEvents, JSX.SyModelessGroup>({
    tagName: 'sy-modeless-group',
    elementClass: SyModelessGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyModelessGroupEvents,
    defineCustomElement: defineSyModelessGroup
});

export type SyNavEvents = NonNullable<unknown>;

export const SyNav: StencilReactComponent<SyNavElement, SyNavEvents, JSX.SyNav> = /*@__PURE__*/ createComponent<SyNavElement, SyNavEvents, JSX.SyNav>({
    tagName: 'sy-nav',
    elementClass: SyNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyNavEvents,
    defineCustomElement: defineSyNav
});

export type SyNavGroupEvents = NonNullable<unknown>;

export const SyNavGroup: StencilReactComponent<SyNavGroupElement, SyNavGroupEvents, JSX.SyNavGroup> = /*@__PURE__*/ createComponent<SyNavGroupElement, SyNavGroupEvents, JSX.SyNavGroup>({
    tagName: 'sy-nav-group',
    elementClass: SyNavGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyNavGroupEvents,
    defineCustomElement: defineSyNavGroup
});

export type SyNavItemEvents = NonNullable<unknown>;

export const SyNavItem: StencilReactComponent<SyNavItemElement, SyNavItemEvents, JSX.SyNavItem> = /*@__PURE__*/ createComponent<SyNavItemElement, SyNavItemEvents, JSX.SyNavItem>({
    tagName: 'sy-nav-item',
    elementClass: SyNavItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyNavItemEvents,
    defineCustomElement: defineSyNavItem
});

export type SyNavSubEvents = NonNullable<unknown>;

export const SyNavSub: StencilReactComponent<SyNavSubElement, SyNavSubEvents, JSX.SyNavSub> = /*@__PURE__*/ createComponent<SyNavSubElement, SyNavSubEvents, JSX.SyNavSub>({
    tagName: 'sy-nav-sub',
    elementClass: SyNavSubElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyNavSubEvents,
    defineCustomElement: defineSyNavSub
});

export type SyOptionEvents = { onActivated: EventName<SyOptionCustomEvent<{ value: string; label: string }>> };

export const SyOption: StencilReactComponent<SyOptionElement, SyOptionEvents, JSX.SyOption> = /*@__PURE__*/ createComponent<SyOptionElement, SyOptionEvents, JSX.SyOption>({
    tagName: 'sy-option',
    elementClass: SyOptionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onActivated: 'activated' } as SyOptionEvents,
    defineCustomElement: defineSyOption
});

export type SyPaginationEvents = {
    onPageChanged: EventName<SyPaginationCustomEvent<number>>,
    onPageSizeChanged: EventName<SyPaginationCustomEvent<number>>
};

export const SyPagination: StencilReactComponent<SyPaginationElement, SyPaginationEvents, JSX.SyPagination> = /*@__PURE__*/ createComponent<SyPaginationElement, SyPaginationEvents, JSX.SyPagination>({
    tagName: 'sy-pagination',
    elementClass: SyPaginationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onPageChanged: 'pageChanged',
        onPageSizeChanged: 'pageSizeChanged'
    } as SyPaginationEvents,
    defineCustomElement: defineSyPagination
});

export type SyPopconfirmEvents = {
    onVisibleChanged: EventName<SyPopconfirmCustomEvent<boolean>>,
    onSelected: EventName<SyPopconfirmCustomEvent<'ok' | 'cancel'>>
};

export const SyPopconfirm: StencilReactComponent<SyPopconfirmElement, SyPopconfirmEvents, JSX.SyPopconfirm> = /*@__PURE__*/ createComponent<SyPopconfirmElement, SyPopconfirmEvents, JSX.SyPopconfirm>({
    tagName: 'sy-popconfirm',
    elementClass: SyPopconfirmElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onVisibleChanged: 'visibleChanged',
        onSelected: 'selected'
    } as SyPopconfirmEvents,
    defineCustomElement: defineSyPopconfirm
});

export type SyPopoverEvents = NonNullable<unknown>;

export const SyPopover: StencilReactComponent<SyPopoverElement, SyPopoverEvents, JSX.SyPopover> = /*@__PURE__*/ createComponent<SyPopoverElement, SyPopoverEvents, JSX.SyPopover>({
    tagName: 'sy-popover',
    elementClass: SyPopoverElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyPopoverEvents,
    defineCustomElement: defineSyPopover
});

export type SyProgressBarEvents = NonNullable<unknown>;

export const SyProgressBar: StencilReactComponent<SyProgressBarElement, SyProgressBarEvents, JSX.SyProgressBar> = /*@__PURE__*/ createComponent<SyProgressBarElement, SyProgressBarEvents, JSX.SyProgressBar>({
    tagName: 'sy-progress-bar',
    elementClass: SyProgressBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyProgressBarEvents,
    defineCustomElement: defineSyProgressBar
});

export type SyProgressCircularEvents = NonNullable<unknown>;

export const SyProgressCircular: StencilReactComponent<SyProgressCircularElement, SyProgressCircularEvents, JSX.SyProgressCircular> = /*@__PURE__*/ createComponent<SyProgressCircularElement, SyProgressCircularEvents, JSX.SyProgressCircular>({
    tagName: 'sy-progress-circular',
    elementClass: SyProgressCircularElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyProgressCircularEvents,
    defineCustomElement: defineSyProgressCircular
});

export type SyRadioEvents = { onSelected: EventName<SyRadioCustomEvent<string>> };

export const SyRadio: StencilReactComponent<SyRadioElement, SyRadioEvents, JSX.SyRadio> = /*@__PURE__*/ createComponent<SyRadioElement, SyRadioEvents, JSX.SyRadio>({
    tagName: 'sy-radio',
    elementClass: SyRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyRadioEvents,
    defineCustomElement: defineSyRadio
});

export type SyRadioButtonEvents = { onSelected: EventName<SyRadioButtonCustomEvent<string>> };

export const SyRadioButton: StencilReactComponent<SyRadioButtonElement, SyRadioButtonEvents, JSX.SyRadioButton> = /*@__PURE__*/ createComponent<SyRadioButtonElement, SyRadioButtonEvents, JSX.SyRadioButton>({
    tagName: 'sy-radio-button',
    elementClass: SyRadioButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyRadioButtonEvents,
    defineCustomElement: defineSyRadioButton
});

export type SyRadioGroupEvents = { onChanged: EventName<SyRadioGroupCustomEvent<{ value: string; isValid: boolean; status: string }>> };

export const SyRadioGroup: StencilReactComponent<SyRadioGroupElement, SyRadioGroupEvents, JSX.SyRadioGroup> = /*@__PURE__*/ createComponent<SyRadioGroupElement, SyRadioGroupEvents, JSX.SyRadioGroup>({
    tagName: 'sy-radio-group',
    elementClass: SyRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SyRadioGroupEvents,
    defineCustomElement: defineSyRadioGroup
});

export type SyRangeCalendarEvents = { onSelected: EventName<SyRangeCalendarCustomEvent<any>> };

export const SyRangeCalendar: StencilReactComponent<SyRangeCalendarElement, SyRangeCalendarEvents, JSX.SyRangeCalendar> = /*@__PURE__*/ createComponent<SyRangeCalendarElement, SyRangeCalendarEvents, JSX.SyRangeCalendar>({
    tagName: 'sy-range-calendar',
    elementClass: SyRangeCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyRangeCalendarEvents,
    defineCustomElement: defineSyRangeCalendar
});

export type SySelectEvents = {
    onOpened: EventName<SySelectCustomEvent<void>>,
    onRemoved: EventName<SySelectCustomEvent<any>>,
    onSelected: EventName<SySelectCustomEvent<any>>,
    onFocused: EventName<SySelectCustomEvent<void>>,
    onBlured: EventName<SySelectCustomEvent<void>>,
    onInputChanged: EventName<SySelectCustomEvent<string>>,
    onCleared: EventName<SySelectCustomEvent<void>>
};

export const SySelect: StencilReactComponent<SySelectElement, SySelectEvents, JSX.SySelect> = /*@__PURE__*/ createComponent<SySelectElement, SySelectEvents, JSX.SySelect>({
    tagName: 'sy-select',
    elementClass: SySelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpened: 'opened',
        onRemoved: 'removed',
        onSelected: 'selected',
        onFocused: 'focused',
        onBlured: 'blured',
        onInputChanged: 'inputChanged',
        onCleared: 'cleared'
    } as SySelectEvents,
    defineCustomElement: defineSySelect
});

export type SySkeletonEvents = NonNullable<unknown>;

export const SySkeleton: StencilReactComponent<SySkeletonElement, SySkeletonEvents, JSX.SySkeleton> = /*@__PURE__*/ createComponent<SySkeletonElement, SySkeletonEvents, JSX.SySkeleton>({
    tagName: 'sy-skeleton',
    elementClass: SySkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SySkeletonEvents,
    defineCustomElement: defineSySkeleton
});

export type SySliderEvents = NonNullable<unknown>;

export const SySlider: StencilReactComponent<SySliderElement, SySliderEvents, JSX.SySlider> = /*@__PURE__*/ createComponent<SySliderElement, SySliderEvents, JSX.SySlider>({
    tagName: 'sy-slider',
    elementClass: SySliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SySliderEvents,
    defineCustomElement: defineSySlider
});

export type SySpinnerEvents = NonNullable<unknown>;

export const SySpinner: StencilReactComponent<SySpinnerElement, SySpinnerEvents, JSX.SySpinner> = /*@__PURE__*/ createComponent<SySpinnerElement, SySpinnerEvents, JSX.SySpinner>({
    tagName: 'sy-spinner',
    elementClass: SySpinnerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SySpinnerEvents,
    defineCustomElement: defineSySpinner
});

export type SySplitPanelEvents = {
    onHorizontalChanged: EventName<SySplitPanelCustomEvent<{ leftRatio: number; rightRatio: number; }>>,
    onVerticalChanged: EventName<SySplitPanelCustomEvent<{ topRatio: number; bottomRatio: number; }>>
};

export const SySplitPanel: StencilReactComponent<SySplitPanelElement, SySplitPanelEvents, JSX.SySplitPanel> = /*@__PURE__*/ createComponent<SySplitPanelElement, SySplitPanelEvents, JSX.SySplitPanel>({
    tagName: 'sy-split-panel',
    elementClass: SySplitPanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onHorizontalChanged: 'horizontalChanged',
        onVerticalChanged: 'verticalChanged'
    } as SySplitPanelEvents,
    defineCustomElement: defineSySplitPanel
});

export type SyStepEvents = NonNullable<unknown>;

export const SyStep: StencilReactComponent<SyStepElement, SyStepEvents, JSX.SyStep> = /*@__PURE__*/ createComponent<SyStepElement, SyStepEvents, JSX.SyStep>({
    tagName: 'sy-step',
    elementClass: SyStepElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyStepEvents,
    defineCustomElement: defineSyStep
});

export type SyStepsEvents = NonNullable<unknown>;

export const SySteps: StencilReactComponent<SyStepsElement, SyStepsEvents, JSX.SySteps> = /*@__PURE__*/ createComponent<SyStepsElement, SyStepsEvents, JSX.SySteps>({
    tagName: 'sy-steps',
    elementClass: SyStepsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyStepsEvents,
    defineCustomElement: defineSySteps
});

export type SySwitchEvents = { onChanged: EventName<SySwitchCustomEvent<boolean>> };

export const SySwitch: StencilReactComponent<SySwitchElement, SySwitchEvents, JSX.SySwitch> = /*@__PURE__*/ createComponent<SySwitchElement, SySwitchEvents, JSX.SySwitch>({
    tagName: 'sy-switch',
    elementClass: SySwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SySwitchEvents,
    defineCustomElement: defineSySwitch
});

export type SyTabEvents = {
    onSelected: EventName<SyTabCustomEvent<any>>,
    onClosed: EventName<SyTabCustomEvent<any>>
};

export const SyTab: StencilReactComponent<SyTabElement, SyTabEvents, JSX.SyTab> = /*@__PURE__*/ createComponent<SyTabElement, SyTabEvents, JSX.SyTab>({
    tagName: 'sy-tab',
    elementClass: SyTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onClosed: 'closed'
    } as SyTabEvents,
    defineCustomElement: defineSyTab
});

export type SyTabContentEvents = NonNullable<unknown>;

export const SyTabContent: StencilReactComponent<SyTabContentElement, SyTabContentEvents, JSX.SyTabContent> = /*@__PURE__*/ createComponent<SyTabContentElement, SyTabContentEvents, JSX.SyTabContent>({
    tagName: 'sy-tab-content',
    elementClass: SyTabContentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyTabContentEvents,
    defineCustomElement: defineSyTabContent
});

export type SyTabGroupEvents = {
    onSelected: EventName<SyTabGroupCustomEvent<any>>,
    onClosed: EventName<SyTabGroupCustomEvent<any>>,
    onOrdered: EventName<SyTabGroupCustomEvent<HTMLSyTabElement[]>>,
    onTabSelected: EventName<SyTabGroupCustomEvent<{ index: number; value: string }>>,
    onTabClosed: EventName<SyTabGroupCustomEvent<{ index: number; value: string }>>,
    onTabAdded: EventName<SyTabGroupCustomEvent<void>>
};

export const SyTabGroup: StencilReactComponent<SyTabGroupElement, SyTabGroupEvents, JSX.SyTabGroup> = /*@__PURE__*/ createComponent<SyTabGroupElement, SyTabGroupEvents, JSX.SyTabGroup>({
    tagName: 'sy-tab-group',
    elementClass: SyTabGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onClosed: 'closed',
        onOrdered: 'ordered',
        onTabSelected: 'tabSelected',
        onTabClosed: 'tabClosed',
        onTabAdded: 'tabAdded'
    } as SyTabGroupEvents,
    defineCustomElement: defineSyTabGroup
});

export type SyTagEvents = {
    onSelected: EventName<SyTagCustomEvent<{ tag: HTMLSyTagElement }>>,
    onRemoved: EventName<SyTagCustomEvent<{ tag: HTMLSyTagElement }>>
};

export const SyTag: StencilReactComponent<SyTagElement, SyTagEvents, JSX.SyTag> = /*@__PURE__*/ createComponent<SyTagElement, SyTagEvents, JSX.SyTag>({
    tagName: 'sy-tag',
    elementClass: SyTagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onRemoved: 'removed'
    } as SyTagEvents,
    defineCustomElement: defineSyTag
});

export type SyTextareaEvents = {
    onChanged: EventName<SyTextareaCustomEvent<{ value: string; length: number; isValid: boolean; status: string }>>,
    onBlured: EventName<SyTextareaCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onFocused: EventName<SyTextareaCustomEvent<{ value: string; isValid: boolean; status: string }>>
};

export const SyTextarea: StencilReactComponent<SyTextareaElement, SyTextareaEvents, JSX.SyTextarea> = /*@__PURE__*/ createComponent<SyTextareaElement, SyTextareaEvents, JSX.SyTextarea>({
    tagName: 'sy-textarea',
    elementClass: SyTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onBlured: 'blured',
        onFocused: 'focused'
    } as SyTextareaEvents,
    defineCustomElement: defineSyTextarea
});

export type SyTimepickerEvents = {
    onSelected: EventName<SyTimepickerCustomEvent<any>>,
    onChanged: EventName<SyTimepickerCustomEvent<any>>
};

export const SyTimepicker: StencilReactComponent<SyTimepickerElement, SyTimepickerEvents, JSX.SyTimepicker> = /*@__PURE__*/ createComponent<SyTimepickerElement, SyTimepickerEvents, JSX.SyTimepicker>({
    tagName: 'sy-timepicker',
    elementClass: SyTimepickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onChanged: 'changed'
    } as SyTimepickerEvents,
    defineCustomElement: defineSyTimepicker
});

export type SyToastEvents = NonNullable<unknown>;

export const SyToast: StencilReactComponent<SyToastElement, SyToastEvents, JSX.SyToast> = /*@__PURE__*/ createComponent<SyToastElement, SyToastEvents, JSX.SyToast>({
    tagName: 'sy-toast',
    elementClass: SyToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyToastEvents,
    defineCustomElement: defineSyToast
});

export type SyToastItemEvents = NonNullable<unknown>;

export const SyToastItem: StencilReactComponent<SyToastItemElement, SyToastItemEvents, JSX.SyToastItem> = /*@__PURE__*/ createComponent<SyToastItemElement, SyToastItemEvents, JSX.SyToastItem>({
    tagName: 'sy-toast-item',
    elementClass: SyToastItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyToastItemEvents,
    defineCustomElement: defineSyToastItem
});

export type SyTooltipEvents = NonNullable<unknown>;

export const SyTooltip: StencilReactComponent<SyTooltipElement, SyTooltipEvents, JSX.SyTooltip> = /*@__PURE__*/ createComponent<SyTooltipElement, SyTooltipEvents, JSX.SyTooltip>({
    tagName: 'sy-tooltip',
    elementClass: SyTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyTooltipEvents,
    defineCustomElement: defineSyTooltip
});

export type SyTreeEvents = {
    onNodesChanged: EventName<SyTreeCustomEvent<{ nodes: TreeNode[] }>>,
    onItemChecked: EventName<SyTreeCustomEvent<{ value: string; label: string; checked: boolean }>>,
    onItemSelected: EventName<SyTreeCustomEvent<{ value: string; label: string; checked: boolean }>>
};

export const SyTree: StencilReactComponent<SyTreeElement, SyTreeEvents, JSX.SyTree> = /*@__PURE__*/ createComponent<SyTreeElement, SyTreeEvents, JSX.SyTree>({
    tagName: 'sy-tree',
    elementClass: SyTreeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onNodesChanged: 'nodesChanged',
        onItemChecked: 'itemChecked',
        onItemSelected: 'itemSelected'
    } as SyTreeEvents,
    defineCustomElement: defineSyTree
});

export type SyTreeItemEvents = {
    onExpandChanged: EventName<SyTreeItemCustomEvent<{ value: string; label: string; expanded: boolean }>>,
    onCheckChanged: EventName<SyTreeItemCustomEvent<{ value: string; label: string; checked: boolean }>>,
    onItemAdded: EventName<SyTreeItemCustomEvent<{ parentValue: string; childLabel: string; childValue: string; childLevel: number }>>,
    onItemRemoved: EventName<SyTreeItemCustomEvent<{ value: string; label: string }>>,
    onItemEdited: EventName<SyTreeItemCustomEvent<{ value: string; label: string }>>,
    onItemUpdating: EventName<SyTreeItemCustomEvent<any>>,
    onItemUpdatingReset: EventName<SyTreeItemCustomEvent<any>>,
    onItemDrop: EventName<SyTreeItemCustomEvent<{ targetKey: string; draggedKey: string; dropPosition: string; targetLevel: number }>>,
    onItemSelected: EventName<SyTreeItemCustomEvent<{ value: string; label: string; checked: boolean }>>,
    onDraggingEvent: EventName<SyTreeItemCustomEvent<string>>
};

export const SyTreeItem: StencilReactComponent<SyTreeItemElement, SyTreeItemEvents, JSX.SyTreeItem> = /*@__PURE__*/ createComponent<SyTreeItemElement, SyTreeItemEvents, JSX.SyTreeItem>({
    tagName: 'sy-tree-item',
    elementClass: SyTreeItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onExpandChanged: 'expandChanged',
        onCheckChanged: 'checkChanged',
        onItemAdded: 'itemAdded',
        onItemRemoved: 'itemRemoved',
        onItemEdited: 'itemEdited',
        onItemUpdating: 'itemUpdating',
        onItemUpdatingReset: 'itemUpdatingReset',
        onItemDrop: 'itemDrop',
        onItemSelected: 'itemSelected',
        onDraggingEvent: 'draggingEvent'
    } as SyTreeItemEvents,
    defineCustomElement: defineSyTreeItem
});

export type SyTreeSelectEvents = { onChanged: EventName<SyTreeSelectCustomEvent<{ selectedItem: { value: string; label: string }[]; isValid: boolean }>> };

export const SyTreeSelect: StencilReactComponent<SyTreeSelectElement, SyTreeSelectEvents, JSX.SyTreeSelect> = /*@__PURE__*/ createComponent<SyTreeSelectElement, SyTreeSelectEvents, JSX.SyTreeSelect>({
    tagName: 'sy-tree-select',
    elementClass: SyTreeSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SyTreeSelectEvents,
    defineCustomElement: defineSyTreeSelect
});
