'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyAutocompleteOptionCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyAutocompleteOption as SyAutocompleteOptionElement, defineCustomElement as defineSyAutocompleteOption } from "@dc/synergy/components/sy-autocomplete-option.js";

export type SyAutocompleteOptionEvents = {
    onActiveChanged: EventName<SyAutocompleteOptionCustomEvent<number>>,
    onSelected: EventName<SyAutocompleteOptionCustomEvent<string>>
};

export const SyAutocompleteOption: StencilReactComponent<SyAutocompleteOptionElement, SyAutocompleteOptionEvents, JSX.SyAutocompleteOption> = /*@__PURE__*/ createComponent<SyAutocompleteOptionElement, SyAutocompleteOptionEvents, JSX.SyAutocompleteOption>({
    tagName: 'sy-autocomplete-option',
    elementClass: SyAutocompleteOptionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onActiveChanged: 'activeChanged',
        onSelected: 'selected'
    } as SyAutocompleteOptionEvents,
    defineCustomElement: defineSyAutocompleteOption
});
