'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyAvatarGroupCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyAvatarGroup as SyAvatarGroupElement, defineCustomElement as defineSyAvatarGroup } from "@dc/synergy/components/sy-avatar-group.js";

export type SyAvatarGroupEvents = { onSelected: EventName<SyAvatarGroupCustomEvent<{ letter: string; text: string; icon: string; image: string; }>> };

export const SyAvatarGroup: StencilReactComponent<SyAvatarGroupElement, SyAvatarGroupEvents, JSX.SyAvatarGroup> = /*@__PURE__*/ createComponent<SyAvatarGroupElement, SyAvatarGroupEvents, JSX.SyAvatarGroup>({
    tagName: 'sy-avatar-group',
    elementClass: SyAvatarGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyAvatarGroupEvents,
    defineCustomElement: defineSyAvatarGroup
});
