'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyAutocompleteCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyAutocomplete as SyAutocompleteElement, defineCustomElement as defineSyAutocomplete } from "@dc/synergy/components/sy-autocomplete.js";

export type SyAutocompleteEvents = {
    onChanged: EventName<SyAutocompleteCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onSelected: EventName<SyAutocompleteCustomEvent<{ value: string; isValid: boolean; status: string }>>
};

export const SyAutocomplete: StencilReactComponent<SyAutocompleteElement, SyAutocompleteEvents, JSX.SyAutocomplete> = /*@__PURE__*/ createComponent<SyAutocompleteElement, SyAutocompleteEvents, JSX.SyAutocomplete>({
    tagName: 'sy-autocomplete',
    elementClass: SyAutocompleteElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onSelected: 'selected'
    } as SyAutocompleteEvents,
    defineCustomElement: defineSyAutocomplete
});
