'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyAvatarCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyAvatar as SyAvatarElement, defineCustomElement as defineSyAvatar } from "@dc/synergy/components/sy-avatar.js";

export type SyAvatarEvents = {
    onSelected: EventName<SyAvatarCustomEvent<{ letter: string; text: string; icon: string; image: string; }>>,
    onDisableStatus: EventName<SyAvatarCustomEvent<{ disabled: boolean }>>
};

export const SyAvatar: StencilReactComponent<SyAvatarElement, SyAvatarEvents, JSX.SyAvatar> = /*@__PURE__*/ createComponent<SyAvatarElement, SyAvatarEvents, JSX.SyAvatar>({
    tagName: 'sy-avatar',
    elementClass: SyAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onDisableStatus: 'disableStatus'
    } as SyAvatarEvents,
    defineCustomElement: defineSyAvatar
});
