'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyBadge as SyBadgeElement, defineCustomElement as defineSyBadge } from "@dc/synergy/components/sy-badge.js";

export type SyBadgeEvents = NonNullable<unknown>;

export const SyBadge: StencilReactComponent<SyBadgeElement, SyBadgeEvents, JSX.SyBadge> = /*@__PURE__*/ createComponent<SyBadgeElement, SyBadgeEvents, JSX.SyBadge>({
    tagName: 'sy-badge',
    elementClass: SyBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyBadgeEvents,
    defineCustomElement: defineSyBadge
});
