'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyBreadcrumb as SyBreadcrumbElement, defineCustomElement as defineSyBreadcrumb } from "@dc/synergy/components/sy-breadcrumb.js";

export type SyBreadcrumbEvents = NonNullable<unknown>;

export const SyBreadcrumb: StencilReactComponent<SyBreadcrumbElement, SyBreadcrumbEvents, JSX.SyBreadcrumb> = /*@__PURE__*/ createComponent<SyBreadcrumbElement, SyBreadcrumbEvents, JSX.SyBreadcrumb>({
    tagName: 'sy-breadcrumb',
    elementClass: SyBreadcrumbElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyBreadcrumbEvents,
    defineCustomElement: defineSyBreadcrumb
});
