'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyButtonGroup as SyButtonGroupElement, defineCustomElement as defineSyButtonGroup } from "@dc/synergy/components/sy-button-group.js";

export type SyButtonGroupEvents = NonNullable<unknown>;

export const SyButtonGroup: StencilReactComponent<SyButtonGroupElement, SyButtonGroupEvents, JSX.SyButtonGroup> = /*@__PURE__*/ createComponent<SyButtonGroupElement, SyButtonGroupEvents, JSX.SyButtonGroup>({
    tagName: 'sy-button-group',
    elementClass: SyButtonGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyButtonGroupEvents,
    defineCustomElement: defineSyButtonGroup
});
