'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyBreadcrumbItemCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyBreadcrumbItem as SyBreadcrumbItemElement, defineCustomElement as defineSyBreadcrumbItem } from "@dc/synergy/components/sy-breadcrumb-item.js";

export type SyBreadcrumbItemEvents = { onSelected: EventName<SyBreadcrumbItemCustomEvent<HTMLSyBreadcrumbItemElement>> };

export const SyBreadcrumbItem: StencilReactComponent<SyBreadcrumbItemElement, SyBreadcrumbItemEvents, JSX.SyBreadcrumbItem> = /*@__PURE__*/ createComponent<SyBreadcrumbItemElement, SyBreadcrumbItemEvents, JSX.SyBreadcrumbItem>({
    tagName: 'sy-breadcrumb-item',
    elementClass: SyBreadcrumbItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyBreadcrumbItemEvents,
    defineCustomElement: defineSyBreadcrumbItem
});
