'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyButton as SyButtonElement, defineCustomElement as defineSyButton } from "@dc/synergy/components/sy-button.js";

export type SyButtonEvents = NonNullable<unknown>;

export const SyButton: StencilReactComponent<SyButtonElement, SyButtonEvents, JSX.SyButton> = /*@__PURE__*/ createComponent<SyButtonElement, SyButtonEvents, JSX.SyButton>({
    tagName: 'sy-button',
    elementClass: SyButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyButtonEvents,
    defineCustomElement: defineSyButton
});
