'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyColorpickerCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyColorpicker as SyColorpickerElement, defineCustomElement as defineSyColorpicker } from "@dc/synergy/components/sy-colorpicker.js";

export type SyColorpickerEvents = { onChanged: EventName<SyColorpickerCustomEvent<{ value: string; format: string; opacity: number }>> };

export const SyColorpicker: StencilReactComponent<SyColorpickerElement, SyColorpickerEvents, JSX.SyColorpicker> = /*@__PURE__*/ createComponent<SyColorpickerElement, SyColorpickerEvents, JSX.SyColorpicker>({
    tagName: 'sy-colorpicker',
    elementClass: SyColorpickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SyColorpickerEvents,
    defineCustomElement: defineSyColorpicker
});
