'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyCheckboxCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyCheckbox as SyCheckboxElement, defineCustomElement as defineSyCheckbox } from "@dc/synergy/components/sy-checkbox.js";

export type SyCheckboxEvents = {
    onChanged: EventName<SyCheckboxCustomEvent<{ value: boolean; isValid: boolean; checked: boolean; indeterminate: boolean }>>,
    onFocused: EventName<SyCheckboxCustomEvent<boolean>>,
    onBlured: EventName<SyCheckboxCustomEvent<boolean>>
};

export const SyCheckbox: StencilReactComponent<SyCheckboxElement, SyCheckboxEvents, JSX.SyCheckbox> = /*@__PURE__*/ createComponent<SyCheckboxElement, SyCheckboxEvents, JSX.SyCheckbox>({
    tagName: 'sy-checkbox',
    elementClass: SyCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onFocused: 'focused',
        onBlured: 'blured'
    } as SyCheckboxEvents,
    defineCustomElement: defineSyCheckbox
});
