'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyColorpickerContentCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyColorpickerContent as SyColorpickerContentElement, defineCustomElement as defineSyColorpickerContent } from "@dc/synergy/components/sy-colorpicker-content.js";

export type SyColorpickerContentEvents = { onColorChange: EventName<SyColorpickerContentCustomEvent<{ value: string; opacity: number; format: string }>> };

export const SyColorpickerContent: StencilReactComponent<SyColorpickerContentElement, SyColorpickerContentEvents, JSX.SyColorpickerContent> = /*@__PURE__*/ createComponent<SyColorpickerContentElement, SyColorpickerContentEvents, JSX.SyColorpickerContent>({
    tagName: 'sy-colorpicker-content',
    elementClass: SyColorpickerContentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onColorChange: 'colorChange' } as SyColorpickerContentEvents,
    defineCustomElement: defineSyColorpickerContent
});
