'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyCalendarCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyCalendar as SyCalendarElement, defineCustomElement as defineSyCalendar } from "@dc/synergy/components/sy-calendar.js";

export type SyCalendarEvents = {
    onSelected: EventName<SyCalendarCustomEvent<any>>,
    onClosed: EventName<SyCalendarCustomEvent<any>>
};

export const SyCalendar: StencilReactComponent<SyCalendarElement, SyCalendarEvents, JSX.SyCalendar> = /*@__PURE__*/ createComponent<SyCalendarElement, SyCalendarEvents, JSX.SyCalendar>({
    tagName: 'sy-calendar',
    elementClass: SyCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onClosed: 'closed'
    } as SyCalendarEvents,
    defineCustomElement: defineSyCalendar
});
