'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyCard as SyCardElement, defineCustomElement as defineSyCard } from "@dc/synergy/components/sy-card.js";

export type SyCardEvents = NonNullable<unknown>;

export const SyCard: StencilReactComponent<SyCardElement, SyCardEvents, JSX.SyCard> = /*@__PURE__*/ createComponent<SyCardElement, SyCardEvents, JSX.SyCard>({
    tagName: 'sy-card',
    elementClass: SyCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyCardEvents,
    defineCustomElement: defineSyCard
});
