'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyCollapse as SyCollapseElement, defineCustomElement as defineSyCollapse } from "@dc/synergy/components/sy-collapse.js";

export type SyCollapseEvents = NonNullable<unknown>;

export const SyCollapse: StencilReactComponent<SyCollapseElement, SyCollapseEvents, JSX.SyCollapse> = /*@__PURE__*/ createComponent<SyCollapseElement, SyCollapseEvents, JSX.SyCollapse>({
    tagName: 'sy-collapse',
    elementClass: SyCollapseElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyCollapseEvents,
    defineCustomElement: defineSyCollapse
});
