'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CollapsePanelChangeDetail, type SyCollapsePanelCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyCollapsePanel as SyCollapsePanelElement, defineCustomElement as defineSyCollapsePanel } from "@dc/synergy/components/sy-collapse-panel.js";

export type SyCollapsePanelEvents = { onChanged: EventName<SyCollapsePanelCustomEvent<CollapsePanelChangeDetail>> };

export const SyCollapsePanel: StencilReactComponent<SyCollapsePanelElement, SyCollapsePanelEvents, JSX.SyCollapsePanel> = /*@__PURE__*/ createComponent<SyCollapsePanelElement, SyCollapsePanelEvents, JSX.SyCollapsePanel>({
    tagName: 'sy-collapse-panel',
    elementClass: SyCollapsePanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SyCollapsePanelEvents,
    defineCustomElement: defineSyCollapsePanel
});
