'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyDatepickerCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyDatepicker as SyDatepickerElement, defineCustomElement as defineSyDatepicker } from "@dc/synergy/components/sy-datepicker.js";

export type SyDatepickerEvents = {
    onChanged: EventName<SyDatepickerCustomEvent<any>>,
    onSelected: EventName<SyDatepickerCustomEvent<any>>
};

export const SyDatepicker: StencilReactComponent<SyDatepickerElement, SyDatepickerEvents, JSX.SyDatepicker> = /*@__PURE__*/ createComponent<SyDatepickerElement, SyDatepickerEvents, JSX.SyDatepicker>({
    tagName: 'sy-datepicker',
    elementClass: SyDatepickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onSelected: 'selected'
    } as SyDatepickerEvents,
    defineCustomElement: defineSyDatepicker
});
