'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyDateCalendarCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyDateCalendar as SyDateCalendarElement, defineCustomElement as defineSyDateCalendar } from "@dc/synergy/components/sy-date-calendar.js";

export type SyDateCalendarEvents = {
    onChanged: EventName<SyDateCalendarCustomEvent<any>>,
    onSelected: EventName<SyDateCalendarCustomEvent<any>>,
    onEntered: EventName<SyDateCalendarCustomEvent<any>>,
    onModeChanged: EventName<SyDateCalendarCustomEvent<any>>
};

export const SyDateCalendar: StencilReactComponent<SyDateCalendarElement, SyDateCalendarEvents, JSX.SyDateCalendar> = /*@__PURE__*/ createComponent<SyDateCalendarElement, SyDateCalendarEvents, JSX.SyDateCalendar>({
    tagName: 'sy-date-calendar',
    elementClass: SyDateCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onSelected: 'selected',
        onEntered: 'entered',
        onModeChanged: 'mode-changed'
    } as SyDateCalendarEvents,
    defineCustomElement: defineSyDateCalendar
});
