'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyDropdownCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyDropdown as SyDropdownElement, defineCustomElement as defineSyDropdown } from "@dc/synergy/components/sy-dropdown.js";

export type SyDropdownEvents = { onSelected: EventName<SyDropdownCustomEvent<any>> };

export const SyDropdown: StencilReactComponent<SyDropdownElement, SyDropdownEvents, JSX.SyDropdown> = /*@__PURE__*/ createComponent<SyDropdownElement, SyDropdownEvents, JSX.SyDropdown>({
    tagName: 'sy-dropdown',
    elementClass: SyDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyDropdownEvents,
    defineCustomElement: defineSyDropdown
});
