'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyDateTimeCalendarCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyDateTimeCalendar as SyDateTimeCalendarElement, defineCustomElement as defineSyDateTimeCalendar } from "@dc/synergy/components/sy-date-time-calendar.js";

export type SyDateTimeCalendarEvents = { onSelected: EventName<SyDateTimeCalendarCustomEvent<any>> };

export const SyDateTimeCalendar: StencilReactComponent<SyDateTimeCalendarElement, SyDateTimeCalendarEvents, JSX.SyDateTimeCalendar> = /*@__PURE__*/ createComponent<SyDateTimeCalendarElement, SyDateTimeCalendarEvents, JSX.SyDateTimeCalendar>({
    tagName: 'sy-date-time-calendar',
    elementClass: SyDateTimeCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyDateTimeCalendarEvents,
    defineCustomElement: defineSyDateTimeCalendar
});
