'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyDivider as SyDividerElement, defineCustomElement as defineSyDivider } from "@dc/synergy/components/sy-divider.js";

export type SyDividerEvents = NonNullable<unknown>;

export const SyDivider: StencilReactComponent<SyDividerElement, SyDividerEvents, JSX.SyDivider> = /*@__PURE__*/ createComponent<SyDividerElement, SyDividerEvents, JSX.SyDivider>({
    tagName: 'sy-divider',
    elementClass: SyDividerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyDividerEvents,
    defineCustomElement: defineSyDivider
});
