'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyDrawerCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyDrawer as SyDrawerElement, defineCustomElement as defineSyDrawer } from "@dc/synergy/components/sy-drawer.js";

export type SyDrawerEvents = {
    onOpened: EventName<SyDrawerCustomEvent<void>>,
    onClosed: EventName<SyDrawerCustomEvent<void>>
};

export const SyDrawer: StencilReactComponent<SyDrawerElement, SyDrawerEvents, JSX.SyDrawer> = /*@__PURE__*/ createComponent<SyDrawerElement, SyDrawerEvents, JSX.SyDrawer>({
    tagName: 'sy-drawer',
    elementClass: SyDrawerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpened: 'opened',
        onClosed: 'closed'
    } as SyDrawerEvents,
    defineCustomElement: defineSyDrawer
});
