'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyEmpty as SyEmptyElement, defineCustomElement as defineSyEmpty } from "@dc/synergy/components/sy-empty.js";

export type SyEmptyEvents = NonNullable<unknown>;

export const SyEmpty: StencilReactComponent<SyEmptyElement, SyEmptyEvents, JSX.SyEmpty> = /*@__PURE__*/ createComponent<SyEmptyElement, SyEmptyEvents, JSX.SyEmpty>({
    tagName: 'sy-empty',
    elementClass: SyEmptyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyEmptyEvents,
    defineCustomElement: defineSyEmpty
});
