'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyFlex as SyFlexElement, defineCustomElement as defineSyFlex } from "@dc/synergy/components/sy-flex.js";

export type SyFlexEvents = NonNullable<unknown>;

export const SyFlex: StencilReactComponent<SyFlexElement, SyFlexEvents, JSX.SyFlex> = /*@__PURE__*/ createComponent<SyFlexElement, SyFlexEvents, JSX.SyFlex>({
    tagName: 'sy-flex',
    elementClass: SyFlexElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyFlexEvents,
    defineCustomElement: defineSyFlex
});
