'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyGlobalHeaderCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyGlobalHeader as SyGlobalHeaderElement, defineCustomElement as defineSyGlobalHeader } from "@dc/synergy/components/sy-global-header.js";

export type SyGlobalHeaderEvents = {
    onChanged: EventName<SyGlobalHeaderCustomEvent<any>>,
    onActionClick: EventName<SyGlobalHeaderCustomEvent<any>>,
    onSelected: EventName<SyGlobalHeaderCustomEvent<any>>
};

export const SyGlobalHeader: StencilReactComponent<SyGlobalHeaderElement, SyGlobalHeaderEvents, JSX.SyGlobalHeader> = /*@__PURE__*/ createComponent<SyGlobalHeaderElement, SyGlobalHeaderEvents, JSX.SyGlobalHeader>({
    tagName: 'sy-global-header',
    elementClass: SyGlobalHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onActionClick: 'actionClick',
        onSelected: 'selected'
    } as SyGlobalHeaderEvents,
    defineCustomElement: defineSyGlobalHeader
});
