'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyInputCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyInput as SyInputElement, defineCustomElement as defineSyInput } from "@dc/synergy/components/sy-input.js";

export type SyInputEvents = {
    onChanged: EventName<SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onBlured: EventName<SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onFocused: EventName<SyInputCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onClear: EventName<SyInputCustomEvent<void>>
};

export const SyInput: StencilReactComponent<SyInputElement, SyInputEvents, JSX.SyInput> = /*@__PURE__*/ createComponent<SyInputElement, SyInputEvents, JSX.SyInput>({
    tagName: 'sy-input',
    elementClass: SyInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onBlured: 'blured',
        onFocused: 'focused',
        onClear: 'clear'
    } as SyInputEvents,
    defineCustomElement: defineSyInput
});
