'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyInlineMessageCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyInlineMessage as SyInlineMessageElement, defineCustomElement as defineSyInlineMessage } from "@dc/synergy/components/sy-inline-message.js";

export type SyInlineMessageEvents = {
    onActionClick: EventName<SyInlineMessageCustomEvent<MouseEvent>>,
    onBtnClick: EventName<SyInlineMessageCustomEvent<MouseEvent>>,
    onDismiss: EventName<SyInlineMessageCustomEvent<void>>
};

export const SyInlineMessage: StencilReactComponent<SyInlineMessageElement, SyInlineMessageEvents, JSX.SyInlineMessage> = /*@__PURE__*/ createComponent<SyInlineMessageElement, SyInlineMessageEvents, JSX.SyInlineMessage>({
    tagName: 'sy-inline-message',
    elementClass: SyInlineMessageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onActionClick: 'actionClick',
        onBtnClick: 'btnClick',
        onDismiss: 'dismiss'
    } as SyInlineMessageEvents,
    defineCustomElement: defineSyInlineMessage
});
