'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyInputNumberCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyInputNumber as SyInputNumberElement, defineCustomElement as defineSyInputNumber } from "@dc/synergy/components/sy-input-number.js";

export type SyInputNumberEvents = {
    onChanged: EventName<SyInputNumberCustomEvent<{ value: number | null; isValid: boolean; status: string }>>,
    onBlured: EventName<SyInputNumberCustomEvent<{ value: number | null; isValid: boolean; status: string }>>,
    onFocused: EventName<SyInputNumberCustomEvent<{ value: number | null; isValid: boolean; status: string }>>
};

export const SyInputNumber: StencilReactComponent<SyInputNumberElement, SyInputNumberEvents, JSX.SyInputNumber> = /*@__PURE__*/ createComponent<SyInputNumberElement, SyInputNumberEvents, JSX.SyInputNumber>({
    tagName: 'sy-input-number',
    elementClass: SyInputNumberElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onBlured: 'blured',
        onFocused: 'focused'
    } as SyInputNumberEvents,
    defineCustomElement: defineSyInputNumber
});
