'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyIconCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyIcon as SyIconElement, defineCustomElement as defineSyIcon } from "@dc/synergy/components/sy-icon.js";

export type SyIconEvents = { onSelected: EventName<SyIconCustomEvent<{ value: string }>> };

export const SyIcon: StencilReactComponent<SyIconElement, SyIconEvents, JSX.SyIcon> = /*@__PURE__*/ createComponent<SyIconElement, SyIconEvents, JSX.SyIcon>({
    tagName: 'sy-icon',
    elementClass: SyIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyIconEvents,
    defineCustomElement: defineSyIcon
});
