'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyMenuCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyMenu as SyMenuElement, defineCustomElement as defineSyMenu } from "@dc/synergy/components/sy-menu.js";

export type SyMenuEvents = {
    onOpened: EventName<SyMenuCustomEvent<boolean>>,
    onItemSelected: EventName<SyMenuCustomEvent<any>>,
    onItemChecked: EventName<SyMenuCustomEvent<any>>
};

export const SyMenu: StencilReactComponent<SyMenuElement, SyMenuEvents, JSX.SyMenu> = /*@__PURE__*/ createComponent<SyMenuElement, SyMenuEvents, JSX.SyMenu>({
    tagName: 'sy-menu',
    elementClass: SyMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpened: 'opened',
        onItemSelected: 'itemSelected',
        onItemChecked: 'itemChecked'
    } as SyMenuEvents,
    defineCustomElement: defineSyMenu
});
