'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyModelessGroup as SyModelessGroupElement, defineCustomElement as defineSyModelessGroup } from "@dc/synergy/components/sy-modeless-group.js";

export type SyModelessGroupEvents = NonNullable<unknown>;

export const SyModelessGroup: StencilReactComponent<SyModelessGroupElement, SyModelessGroupEvents, JSX.SyModelessGroup> = /*@__PURE__*/ createComponent<SyModelessGroupElement, SyModelessGroupEvents, JSX.SyModelessGroup>({
    tagName: 'sy-modeless-group',
    elementClass: SyModelessGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyModelessGroupEvents,
    defineCustomElement: defineSyModelessGroup
});
