'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyMenuSub as SyMenuSubElement, defineCustomElement as defineSyMenuSub } from "@dc/synergy/components/sy-menu-sub.js";

export type SyMenuSubEvents = NonNullable<unknown>;

export const SyMenuSub: StencilReactComponent<SyMenuSubElement, SyMenuSubEvents, JSX.SyMenuSub> = /*@__PURE__*/ createComponent<SyMenuSubElement, SyMenuSubEvents, JSX.SyMenuSub>({
    tagName: 'sy-menu-sub',
    elementClass: SyMenuSubElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyMenuSubEvents,
    defineCustomElement: defineSyMenuSub
});
