'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyModalCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyModal as SyModalElement, defineCustomElement as defineSyModal } from "@dc/synergy/components/sy-modal.js";

export type SyModalEvents = { onClosed: EventName<SyModalCustomEvent<{ event: 'ok' | 'cancel' | 'close'; value: any; maximized: boolean; position: { top: string; left: string }; }>> };

export const SyModal: StencilReactComponent<SyModalElement, SyModalEvents, JSX.SyModal> = /*@__PURE__*/ createComponent<SyModalElement, SyModalEvents, JSX.SyModal>({
    tagName: 'sy-modal',
    elementClass: SyModalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onClosed: 'closed' } as SyModalEvents,
    defineCustomElement: defineSyModal
});
