'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ModelessPositionChangedDetail, type SyModelessCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyModeless as SyModelessElement, defineCustomElement as defineSyModeless } from "@dc/synergy/components/sy-modeless.js";

export type SyModelessEvents = {
    onClosed: EventName<SyModelessCustomEvent<{ id: string }>>,
    onStatusChanged: EventName<SyModelessCustomEvent<{ id: string; status: string }>>,
    onPositionChanged: EventName<SyModelessCustomEvent<ModelessPositionChangedDetail>>
};

export const SyModeless: StencilReactComponent<SyModelessElement, SyModelessEvents, JSX.SyModeless> = /*@__PURE__*/ createComponent<SyModelessElement, SyModelessEvents, JSX.SyModeless>({
    tagName: 'sy-modeless',
    elementClass: SyModelessElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onClosed: 'closed',
        onStatusChanged: 'statusChanged',
        onPositionChanged: 'positionChanged'
    } as SyModelessEvents,
    defineCustomElement: defineSyModeless
});
