'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyMenuItemCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyMenuItem as SyMenuItemElement, defineCustomElement as defineSyMenuItem } from "@dc/synergy/components/sy-menu-item.js";

export type SyMenuItemEvents = {
    onItemSelected: EventName<SyMenuItemCustomEvent<{ value: string; label: string }>>,
    onItemChecked: EventName<SyMenuItemCustomEvent<{ value: string; label: string; checked: boolean }>>
};

export const SyMenuItem: StencilReactComponent<SyMenuItemElement, SyMenuItemEvents, JSX.SyMenuItem> = /*@__PURE__*/ createComponent<SyMenuItemElement, SyMenuItemEvents, JSX.SyMenuItem>({
    tagName: 'sy-menu-item',
    elementClass: SyMenuItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onItemSelected: 'itemSelected',
        onItemChecked: 'itemChecked'
    } as SyMenuItemEvents,
    defineCustomElement: defineSyMenuItem
});
