'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyMenuGroup as SyMenuGroupElement, defineCustomElement as defineSyMenuGroup } from "@dc/synergy/components/sy-menu-group.js";

export type SyMenuGroupEvents = NonNullable<unknown>;

export const SyMenuGroup: StencilReactComponent<SyMenuGroupElement, SyMenuGroupEvents, JSX.SyMenuGroup> = /*@__PURE__*/ createComponent<SyMenuGroupElement, SyMenuGroupEvents, JSX.SyMenuGroup>({
    tagName: 'sy-menu-group',
    elementClass: SyMenuGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyMenuGroupEvents,
    defineCustomElement: defineSyMenuGroup
});
