'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyNavGroup as SyNavGroupElement, defineCustomElement as defineSyNavGroup } from "@dc/synergy/components/sy-nav-group.js";

export type SyNavGroupEvents = NonNullable<unknown>;

export const SyNavGroup: StencilReactComponent<SyNavGroupElement, SyNavGroupEvents, JSX.SyNavGroup> = /*@__PURE__*/ createComponent<SyNavGroupElement, SyNavGroupEvents, JSX.SyNavGroup>({
    tagName: 'sy-nav-group',
    elementClass: SyNavGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyNavGroupEvents,
    defineCustomElement: defineSyNavGroup
});
