'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyNavSub as SyNavSubElement, defineCustomElement as defineSyNavSub } from "@dc/synergy/components/sy-nav-sub.js";

export type SyNavSubEvents = NonNullable<unknown>;

export const SyNavSub: StencilReactComponent<SyNavSubElement, SyNavSubEvents, JSX.SyNavSub> = /*@__PURE__*/ createComponent<SyNavSubElement, SyNavSubEvents, JSX.SyNavSub>({
    tagName: 'sy-nav-sub',
    elementClass: SyNavSubElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyNavSubEvents,
    defineCustomElement: defineSyNavSub
});
