'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyNavItem as SyNavItemElement, defineCustomElement as defineSyNavItem } from "@dc/synergy/components/sy-nav-item.js";

export type SyNavItemEvents = NonNullable<unknown>;

export const SyNavItem: StencilReactComponent<SyNavItemElement, SyNavItemEvents, JSX.SyNavItem> = /*@__PURE__*/ createComponent<SyNavItemElement, SyNavItemEvents, JSX.SyNavItem>({
    tagName: 'sy-nav-item',
    elementClass: SyNavItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyNavItemEvents,
    defineCustomElement: defineSyNavItem
});
