'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyOptionCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyOption as SyOptionElement, defineCustomElement as defineSyOption } from "@dc/synergy/components/sy-option.js";

export type SyOptionEvents = { onActivated: EventName<SyOptionCustomEvent<{ value: string; label: string }>> };

export const SyOption: StencilReactComponent<SyOptionElement, SyOptionEvents, JSX.SyOption> = /*@__PURE__*/ createComponent<SyOptionElement, SyOptionEvents, JSX.SyOption>({
    tagName: 'sy-option',
    elementClass: SyOptionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onActivated: 'activated' } as SyOptionEvents,
    defineCustomElement: defineSyOption
});
