'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyPopconfirmCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyPopconfirm as SyPopconfirmElement, defineCustomElement as defineSyPopconfirm } from "@dc/synergy/components/sy-popconfirm.js";

export type SyPopconfirmEvents = {
    onVisibleChanged: EventName<SyPopconfirmCustomEvent<boolean>>,
    onSelected: EventName<SyPopconfirmCustomEvent<'ok' | 'cancel'>>
};

export const SyPopconfirm: StencilReactComponent<SyPopconfirmElement, SyPopconfirmEvents, JSX.SyPopconfirm> = /*@__PURE__*/ createComponent<SyPopconfirmElement, SyPopconfirmEvents, JSX.SyPopconfirm>({
    tagName: 'sy-popconfirm',
    elementClass: SyPopconfirmElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onVisibleChanged: 'visibleChanged',
        onSelected: 'selected'
    } as SyPopconfirmEvents,
    defineCustomElement: defineSyPopconfirm
});
