'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyProgressCircular as SyProgressCircularElement, defineCustomElement as defineSyProgressCircular } from "@dc/synergy/components/sy-progress-circular.js";

export type SyProgressCircularEvents = NonNullable<unknown>;

export const SyProgressCircular: StencilReactComponent<SyProgressCircularElement, SyProgressCircularEvents, JSX.SyProgressCircular> = /*@__PURE__*/ createComponent<SyProgressCircularElement, SyProgressCircularEvents, JSX.SyProgressCircular>({
    tagName: 'sy-progress-circular',
    elementClass: SyProgressCircularElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyProgressCircularEvents,
    defineCustomElement: defineSyProgressCircular
});
