'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyProgressBar as SyProgressBarElement, defineCustomElement as defineSyProgressBar } from "@dc/synergy/components/sy-progress-bar.js";

export type SyProgressBarEvents = NonNullable<unknown>;

export const SyProgressBar: StencilReactComponent<SyProgressBarElement, SyProgressBarEvents, JSX.SyProgressBar> = /*@__PURE__*/ createComponent<SyProgressBarElement, SyProgressBarEvents, JSX.SyProgressBar>({
    tagName: 'sy-progress-bar',
    elementClass: SyProgressBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyProgressBarEvents,
    defineCustomElement: defineSyProgressBar
});
