'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyPaginationCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyPagination as SyPaginationElement, defineCustomElement as defineSyPagination } from "@dc/synergy/components/sy-pagination.js";

export type SyPaginationEvents = {
    onPageChanged: EventName<SyPaginationCustomEvent<number>>,
    onPageSizeChanged: EventName<SyPaginationCustomEvent<number>>
};

export const SyPagination: StencilReactComponent<SyPaginationElement, SyPaginationEvents, JSX.SyPagination> = /*@__PURE__*/ createComponent<SyPaginationElement, SyPaginationEvents, JSX.SyPagination>({
    tagName: 'sy-pagination',
    elementClass: SyPaginationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onPageChanged: 'pageChanged',
        onPageSizeChanged: 'pageSizeChanged'
    } as SyPaginationEvents,
    defineCustomElement: defineSyPagination
});
