'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyPopover as SyPopoverElement, defineCustomElement as defineSyPopover } from "@dc/synergy/components/sy-popover.js";

export type SyPopoverEvents = NonNullable<unknown>;

export const SyPopover: StencilReactComponent<SyPopoverElement, SyPopoverEvents, JSX.SyPopover> = /*@__PURE__*/ createComponent<SyPopoverElement, SyPopoverEvents, JSX.SyPopover>({
    tagName: 'sy-popover',
    elementClass: SyPopoverElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyPopoverEvents,
    defineCustomElement: defineSyPopover
});
