'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyRadioButtonCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyRadioButton as SyRadioButtonElement, defineCustomElement as defineSyRadioButton } from "@dc/synergy/components/sy-radio-button.js";

export type SyRadioButtonEvents = { onSelected: EventName<SyRadioButtonCustomEvent<string>> };

export const SyRadioButton: StencilReactComponent<SyRadioButtonElement, SyRadioButtonEvents, JSX.SyRadioButton> = /*@__PURE__*/ createComponent<SyRadioButtonElement, SyRadioButtonEvents, JSX.SyRadioButton>({
    tagName: 'sy-radio-button',
    elementClass: SyRadioButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyRadioButtonEvents,
    defineCustomElement: defineSyRadioButton
});
