'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyRangeCalendarCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyRangeCalendar as SyRangeCalendarElement, defineCustomElement as defineSyRangeCalendar } from "@dc/synergy/components/sy-range-calendar.js";

export type SyRangeCalendarEvents = { onSelected: EventName<SyRangeCalendarCustomEvent<any>> };

export const SyRangeCalendar: StencilReactComponent<SyRangeCalendarElement, SyRangeCalendarEvents, JSX.SyRangeCalendar> = /*@__PURE__*/ createComponent<SyRangeCalendarElement, SyRangeCalendarEvents, JSX.SyRangeCalendar>({
    tagName: 'sy-range-calendar',
    elementClass: SyRangeCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyRangeCalendarEvents,
    defineCustomElement: defineSyRangeCalendar
});
