'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyRadioGroupCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyRadioGroup as SyRadioGroupElement, defineCustomElement as defineSyRadioGroup } from "@dc/synergy/components/sy-radio-group.js";

export type SyRadioGroupEvents = { onChanged: EventName<SyRadioGroupCustomEvent<{ value: string; isValid: boolean; status: string }>> };

export const SyRadioGroup: StencilReactComponent<SyRadioGroupElement, SyRadioGroupEvents, JSX.SyRadioGroup> = /*@__PURE__*/ createComponent<SyRadioGroupElement, SyRadioGroupEvents, JSX.SyRadioGroup>({
    tagName: 'sy-radio-group',
    elementClass: SyRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SyRadioGroupEvents,
    defineCustomElement: defineSyRadioGroup
});
