'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyRadioCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyRadio as SyRadioElement, defineCustomElement as defineSyRadio } from "@dc/synergy/components/sy-radio.js";

export type SyRadioEvents = { onSelected: EventName<SyRadioCustomEvent<string>> };

export const SyRadio: StencilReactComponent<SyRadioElement, SyRadioEvents, JSX.SyRadio> = /*@__PURE__*/ createComponent<SyRadioElement, SyRadioEvents, JSX.SyRadio>({
    tagName: 'sy-radio',
    elementClass: SyRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as SyRadioEvents,
    defineCustomElement: defineSyRadio
});
