'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SySteps as SyStepsElement, defineCustomElement as defineSySteps } from "@dc/synergy/components/sy-steps.js";

export type SyStepsEvents = NonNullable<unknown>;

export const SySteps: StencilReactComponent<SyStepsElement, SyStepsEvents, JSX.SySteps> = /*@__PURE__*/ createComponent<SyStepsElement, SyStepsEvents, JSX.SySteps>({
    tagName: 'sy-steps',
    elementClass: SyStepsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyStepsEvents,
    defineCustomElement: defineSySteps
});
