'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyStep as SyStepElement, defineCustomElement as defineSyStep } from "@dc/synergy/components/sy-step.js";

export type SyStepEvents = NonNullable<unknown>;

export const SyStep: StencilReactComponent<SyStepElement, SyStepEvents, JSX.SyStep> = /*@__PURE__*/ createComponent<SyStepElement, SyStepEvents, JSX.SyStep>({
    tagName: 'sy-step',
    elementClass: SyStepElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyStepEvents,
    defineCustomElement: defineSyStep
});
