'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SySpinner as SySpinnerElement, defineCustomElement as defineSySpinner } from "@dc/synergy/components/sy-spinner.js";

export type SySpinnerEvents = NonNullable<unknown>;

export const SySpinner: StencilReactComponent<SySpinnerElement, SySpinnerEvents, JSX.SySpinner> = /*@__PURE__*/ createComponent<SySpinnerElement, SySpinnerEvents, JSX.SySpinner>({
    tagName: 'sy-spinner',
    elementClass: SySpinnerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SySpinnerEvents,
    defineCustomElement: defineSySpinner
});
