'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SySelectCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SySelect as SySelectElement, defineCustomElement as defineSySelect } from "@dc/synergy/components/sy-select.js";

export type SySelectEvents = {
    onOpened: EventName<SySelectCustomEvent<void>>,
    onRemoved: EventName<SySelectCustomEvent<any>>,
    onSelected: EventName<SySelectCustomEvent<any>>,
    onFocused: EventName<SySelectCustomEvent<void>>,
    onBlured: EventName<SySelectCustomEvent<void>>,
    onInputChanged: EventName<SySelectCustomEvent<string>>,
    onCleared: EventName<SySelectCustomEvent<void>>
};

export const SySelect: StencilReactComponent<SySelectElement, SySelectEvents, JSX.SySelect> = /*@__PURE__*/ createComponent<SySelectElement, SySelectEvents, JSX.SySelect>({
    tagName: 'sy-select',
    elementClass: SySelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpened: 'opened',
        onRemoved: 'removed',
        onSelected: 'selected',
        onFocused: 'focused',
        onBlured: 'blured',
        onInputChanged: 'inputChanged',
        onCleared: 'cleared'
    } as SySelectEvents,
    defineCustomElement: defineSySelect
});
