'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SySplitPanelCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SySplitPanel as SySplitPanelElement, defineCustomElement as defineSySplitPanel } from "@dc/synergy/components/sy-split-panel.js";

export type SySplitPanelEvents = {
    onHorizontalChanged: EventName<SySplitPanelCustomEvent<{ leftRatio: number; rightRatio: number; }>>,
    onVerticalChanged: EventName<SySplitPanelCustomEvent<{ topRatio: number; bottomRatio: number; }>>
};

export const SySplitPanel: StencilReactComponent<SySplitPanelElement, SySplitPanelEvents, JSX.SySplitPanel> = /*@__PURE__*/ createComponent<SySplitPanelElement, SySplitPanelEvents, JSX.SySplitPanel>({
    tagName: 'sy-split-panel',
    elementClass: SySplitPanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onHorizontalChanged: 'horizontalChanged',
        onVerticalChanged: 'verticalChanged'
    } as SySplitPanelEvents,
    defineCustomElement: defineSySplitPanel
});
