'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SySkeleton as SySkeletonElement, defineCustomElement as defineSySkeleton } from "@dc/synergy/components/sy-skeleton.js";

export type SySkeletonEvents = NonNullable<unknown>;

export const SySkeleton: StencilReactComponent<SySkeletonElement, SySkeletonEvents, JSX.SySkeleton> = /*@__PURE__*/ createComponent<SySkeletonElement, SySkeletonEvents, JSX.SySkeleton>({
    tagName: 'sy-skeleton',
    elementClass: SySkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SySkeletonEvents,
    defineCustomElement: defineSySkeleton
});
