'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SySwitchCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SySwitch as SySwitchElement, defineCustomElement as defineSySwitch } from "@dc/synergy/components/sy-switch.js";

export type SySwitchEvents = { onChanged: EventName<SySwitchCustomEvent<boolean>> };

export const SySwitch: StencilReactComponent<SySwitchElement, SySwitchEvents, JSX.SySwitch> = /*@__PURE__*/ createComponent<SySwitchElement, SySwitchEvents, JSX.SySwitch>({
    tagName: 'sy-switch',
    elementClass: SySwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SySwitchEvents,
    defineCustomElement: defineSySwitch
});
