'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SySlider as SySliderElement, defineCustomElement as defineSySlider } from "@dc/synergy/components/sy-slider.js";

export type SySliderEvents = NonNullable<unknown>;

export const SySlider: StencilReactComponent<SySliderElement, SySliderEvents, JSX.SySlider> = /*@__PURE__*/ createComponent<SySliderElement, SySliderEvents, JSX.SySlider>({
    tagName: 'sy-slider',
    elementClass: SySliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SySliderEvents,
    defineCustomElement: defineSySlider
});
