'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyTagCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyTag as SyTagElement, defineCustomElement as defineSyTag } from "@dc/synergy/components/sy-tag.js";

export type SyTagEvents = {
    onSelected: EventName<SyTagCustomEvent<{ tag: HTMLSyTagElement }>>,
    onRemoved: EventName<SyTagCustomEvent<{ tag: HTMLSyTagElement }>>
};

export const SyTag: StencilReactComponent<SyTagElement, SyTagEvents, JSX.SyTag> = /*@__PURE__*/ createComponent<SyTagElement, SyTagEvents, JSX.SyTag>({
    tagName: 'sy-tag',
    elementClass: SyTagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onRemoved: 'removed'
    } as SyTagEvents,
    defineCustomElement: defineSyTag
});
