'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyToast as SyToastElement, defineCustomElement as defineSyToast } from "@dc/synergy/components/sy-toast.js";

export type SyToastEvents = NonNullable<unknown>;

export const SyToast: StencilReactComponent<SyToastElement, SyToastEvents, JSX.SyToast> = /*@__PURE__*/ createComponent<SyToastElement, SyToastEvents, JSX.SyToast>({
    tagName: 'sy-toast',
    elementClass: SyToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyToastEvents,
    defineCustomElement: defineSyToast
});
