'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyTimepickerCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyTimepicker as SyTimepickerElement, defineCustomElement as defineSyTimepicker } from "@dc/synergy/components/sy-timepicker.js";

export type SyTimepickerEvents = {
    onSelected: EventName<SyTimepickerCustomEvent<any>>,
    onChanged: EventName<SyTimepickerCustomEvent<any>>
};

export const SyTimepicker: StencilReactComponent<SyTimepickerElement, SyTimepickerEvents, JSX.SyTimepicker> = /*@__PURE__*/ createComponent<SyTimepickerElement, SyTimepickerEvents, JSX.SyTimepicker>({
    tagName: 'sy-timepicker',
    elementClass: SyTimepickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onChanged: 'changed'
    } as SyTimepickerEvents,
    defineCustomElement: defineSyTimepicker
});
