'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyToastItem as SyToastItemElement, defineCustomElement as defineSyToastItem } from "@dc/synergy/components/sy-toast-item.js";

export type SyToastItemEvents = NonNullable<unknown>;

export const SyToastItem: StencilReactComponent<SyToastItemElement, SyToastItemEvents, JSX.SyToastItem> = /*@__PURE__*/ createComponent<SyToastItemElement, SyToastItemEvents, JSX.SyToastItem>({
    tagName: 'sy-toast-item',
    elementClass: SyToastItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyToastItemEvents,
    defineCustomElement: defineSyToastItem
});
