'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyTreeItemCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyTreeItem as SyTreeItemElement, defineCustomElement as defineSyTreeItem } from "@dc/synergy/components/sy-tree-item.js";

export type SyTreeItemEvents = {
    onExpandChanged: EventName<SyTreeItemCustomEvent<{ value: string; label: string; expanded: boolean }>>,
    onCheckChanged: EventName<SyTreeItemCustomEvent<{ value: string; label: string; checked: boolean }>>,
    onItemAdded: EventName<SyTreeItemCustomEvent<{ parentValue: string; childLabel: string; childValue: string; childLevel: number }>>,
    onItemRemoved: EventName<SyTreeItemCustomEvent<{ value: string; label: string }>>,
    onItemEdited: EventName<SyTreeItemCustomEvent<{ value: string; label: string }>>,
    onItemUpdating: EventName<SyTreeItemCustomEvent<any>>,
    onItemUpdatingReset: EventName<SyTreeItemCustomEvent<any>>,
    onItemDrop: EventName<SyTreeItemCustomEvent<{ targetKey: string; draggedKey: string; dropPosition: string; targetLevel: number }>>,
    onItemSelected: EventName<SyTreeItemCustomEvent<{ value: string; label: string; checked: boolean }>>,
    onDraggingEvent: EventName<SyTreeItemCustomEvent<string>>
};

export const SyTreeItem: StencilReactComponent<SyTreeItemElement, SyTreeItemEvents, JSX.SyTreeItem> = /*@__PURE__*/ createComponent<SyTreeItemElement, SyTreeItemEvents, JSX.SyTreeItem>({
    tagName: 'sy-tree-item',
    elementClass: SyTreeItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onExpandChanged: 'expandChanged',
        onCheckChanged: 'checkChanged',
        onItemAdded: 'itemAdded',
        onItemRemoved: 'itemRemoved',
        onItemEdited: 'itemEdited',
        onItemUpdating: 'itemUpdating',
        onItemUpdatingReset: 'itemUpdatingReset',
        onItemDrop: 'itemDrop',
        onItemSelected: 'itemSelected',
        onDraggingEvent: 'draggingEvent'
    } as SyTreeItemEvents,
    defineCustomElement: defineSyTreeItem
});
