'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyTextareaCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyTextarea as SyTextareaElement, defineCustomElement as defineSyTextarea } from "@dc/synergy/components/sy-textarea.js";

export type SyTextareaEvents = {
    onChanged: EventName<SyTextareaCustomEvent<{ value: string; length: number; isValid: boolean; status: string }>>,
    onBlured: EventName<SyTextareaCustomEvent<{ value: string; isValid: boolean; status: string }>>,
    onFocused: EventName<SyTextareaCustomEvent<{ value: string; isValid: boolean; status: string }>>
};

export const SyTextarea: StencilReactComponent<SyTextareaElement, SyTextareaEvents, JSX.SyTextarea> = /*@__PURE__*/ createComponent<SyTextareaElement, SyTextareaEvents, JSX.SyTextarea>({
    tagName: 'sy-textarea',
    elementClass: SyTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChanged: 'changed',
        onBlured: 'blured',
        onFocused: 'focused'
    } as SyTextareaEvents,
    defineCustomElement: defineSyTextarea
});
