'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyTabCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyTab as SyTabElement, defineCustomElement as defineSyTab } from "@dc/synergy/components/sy-tab.js";

export type SyTabEvents = {
    onSelected: EventName<SyTabCustomEvent<any>>,
    onClosed: EventName<SyTabCustomEvent<any>>
};

export const SyTab: StencilReactComponent<SyTabElement, SyTabEvents, JSX.SyTab> = /*@__PURE__*/ createComponent<SyTabElement, SyTabEvents, JSX.SyTab>({
    tagName: 'sy-tab',
    elementClass: SyTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onClosed: 'closed'
    } as SyTabEvents,
    defineCustomElement: defineSyTab
});
