'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyTooltip as SyTooltipElement, defineCustomElement as defineSyTooltip } from "@dc/synergy/components/sy-tooltip.js";

export type SyTooltipEvents = NonNullable<unknown>;

export const SyTooltip: StencilReactComponent<SyTooltipElement, SyTooltipEvents, JSX.SyTooltip> = /*@__PURE__*/ createComponent<SyTooltipElement, SyTooltipEvents, JSX.SyTooltip>({
    tagName: 'sy-tooltip',
    elementClass: SyTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyTooltipEvents,
    defineCustomElement: defineSyTooltip
});
