'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyTabGroupCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyTabGroup as SyTabGroupElement, defineCustomElement as defineSyTabGroup } from "@dc/synergy/components/sy-tab-group.js";

export type SyTabGroupEvents = {
    onSelected: EventName<SyTabGroupCustomEvent<any>>,
    onClosed: EventName<SyTabGroupCustomEvent<any>>,
    onOrdered: EventName<SyTabGroupCustomEvent<HTMLSyTabElement[]>>,
    onTabSelected: EventName<SyTabGroupCustomEvent<{ index: number; value: string }>>,
    onTabClosed: EventName<SyTabGroupCustomEvent<{ index: number; value: string }>>,
    onTabAdded: EventName<SyTabGroupCustomEvent<void>>
};

export const SyTabGroup: StencilReactComponent<SyTabGroupElement, SyTabGroupEvents, JSX.SyTabGroup> = /*@__PURE__*/ createComponent<SyTabGroupElement, SyTabGroupEvents, JSX.SyTabGroup>({
    tagName: 'sy-tab-group',
    elementClass: SyTabGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelected: 'selected',
        onClosed: 'closed',
        onOrdered: 'ordered',
        onTabSelected: 'tabSelected',
        onTabClosed: 'tabClosed',
        onTabAdded: 'tabAdded'
    } as SyTabGroupEvents,
    defineCustomElement: defineSyTabGroup
});
