'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@dc/synergy/components";
import { SyTabContent as SyTabContentElement, defineCustomElement as defineSyTabContent } from "@dc/synergy/components/sy-tab-content.js";

export type SyTabContentEvents = NonNullable<unknown>;

export const SyTabContent: StencilReactComponent<SyTabContentElement, SyTabContentEvents, JSX.SyTabContent> = /*@__PURE__*/ createComponent<SyTabContentElement, SyTabContentEvents, JSX.SyTabContent>({
    tagName: 'sy-tab-content',
    elementClass: SyTabContentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SyTabContentEvents,
    defineCustomElement: defineSyTabContent
});
