'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyTreeCustomEvent, type TreeNode } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyTree as SyTreeElement, defineCustomElement as defineSyTree } from "@dc/synergy/components/sy-tree.js";

export type SyTreeEvents = {
    onNodesChanged: EventName<SyTreeCustomEvent<{ nodes: TreeNode[] }>>,
    onItemChecked: EventName<SyTreeCustomEvent<{ value: string; label: string; checked: boolean }>>,
    onItemSelected: EventName<SyTreeCustomEvent<{ value: string; label: string; checked: boolean }>>
};

export const SyTree: StencilReactComponent<SyTreeElement, SyTreeEvents, JSX.SyTree> = /*@__PURE__*/ createComponent<SyTreeElement, SyTreeEvents, JSX.SyTree>({
    tagName: 'sy-tree',
    elementClass: SyTreeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onNodesChanged: 'nodesChanged',
        onItemChecked: 'itemChecked',
        onItemSelected: 'itemSelected'
    } as SyTreeEvents,
    defineCustomElement: defineSyTree
});
