'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type SyTreeSelectCustomEvent } from "@dc/synergy";
import type { JSX } from "@dc/synergy/components";
import { SyTreeSelect as SyTreeSelectElement, defineCustomElement as defineSyTreeSelect } from "@dc/synergy/components/sy-tree-select.js";

export type SyTreeSelectEvents = { onChanged: EventName<SyTreeSelectCustomEvent<{ selectedItem: { value: string; label: string }[]; isValid: boolean }>> };

export const SyTreeSelect: StencilReactComponent<SyTreeSelectElement, SyTreeSelectEvents, JSX.SyTreeSelect> = /*@__PURE__*/ createComponent<SyTreeSelectElement, SyTreeSelectEvents, JSX.SyTreeSelect>({
    tagName: 'sy-tree-select',
    elementClass: SyTreeSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as SyTreeSelectEvents,
    defineCustomElement: defineSyTreeSelect
});
